### ISSUE TITLE
Stream decompression uncompleted

### ISSUE THREAD

**Issue by georgesben** [ZJONSSON/node-unzipper#10]
Hi !

I have a little problem with the decompression stream. I don't know why, but there is not all the entries of the zip file (attached below). Here is my code:
```Javascript
function uploadZip(filepath){
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            let filename = entry.path;
            console.log(filename);
            if (isImage(filename)){
                uploadFile(entry);
            }
            else {
                entry.autodrain();
            }
        });
};

```
Actually, I have only two logs which are: WTxBc.jpg and text.txt
Normaly, I should have a second jpg in the log.

Did someone have an idea to solve this problem ?

[Desktop - Copie.zip](https://github.com/ZJONSSON/node-unzipper/files/603961/Desktop.-.Copie.zip)

**Comment by ZJONSSON** [comment]
The entry in this case is a stream so my guess is that the `uploadFile` function does not fully consume the stream, i.e. entry needs to pipe it to a node-compatible stream, writable or a transform.

#### If upload function expects a buffer

If your upload function expects a buffer, then you have to collect all the contents of `entry` before calling the function.  Here is an example of how this can be done with a `stream.Transform`

```js
if (isImage(filename)) {
    // collect contents into a buffer
    entry.pipe(stream.Transform({
        transform: function(d,e,cb) {
            this.buffer = Buffer.concat([this.buffer || new Buffer(''),d]);
            cb();
        }
    }))
    // when entry has finished, then upload the buffer
    .on('finish',function() {
        uploadFile(this.buffer,filename);
    });   
}
```

Here is the full working example (where uploadFile simply writes it to the local directory):
```js
'use strict';
var fs = require('fs');
var unzipper = require('unzipper');
var Buffer = require('buffer').Buffer;
var stream = require('stream');

function isImage(filename) {
    return /\.jpg$/.exec(filename) && true;
}

function uploadFile(buf,name) {
    fs.writeFileSync('./'+name,buf);
}

function uploadZip(filepath){
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            let filename = entry.path;
            console.log(filename);
            if (isImage(filename)){
                // collect contents into a buffer
                entry.pipe(stream.Transform({
                    transform: function(d,e,cb) {
                        this.buffer = Buffer.concat([this.buffer || new Buffer(''),d]);
                        cb();
                    }
                }))
                // when entry has finished, then upload the buffer
                .on('finish',function() {
                    uploadFile(this.buffer,filename);
                });   
            }
            else {
                entry.autodrain();
            }
        });
}

uploadZip('./Desktop.-.Copie.zip');
```

#### If upload function expects a stream

Here is the same example except the upload function will accept (and fully consume) the stream directly:

```js
var unzipper = require('unzipper');

function isImage(filename) {
    return /\.jpg$/.exec(filename) && true;
}

function uploadFile(entry) {
    entry.pipe(fs.createWriteStream('./'+entry.path));
}

function uploadZip(filepath) {
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            let filename = entry.path;
            console.log(filename);
            if (isImage(filename)){
                uploadFile(entry);
            }
            else {
                entry.autodrain();
            }
        });
}

uploadZip('./Desktop.-.Copie.zip');
```

**Comment by ZJONSSON** [comment]
Closing - please reopen with more detail if you still have problems.

**Comment by georgesben** [comment]
Sorry, I was unclear. I have changed my javascript function to be clearer:
```Javascript
function uploadZip(filepath){
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            console.log("entry trigger"); //the new part of the function
            let filename = entry.path;
            console.log(filename);
            if (isImage(filename)){
                uploadFile(entry);
            }
            else {
                entry.autodrain();
            }
        });
};
```
In the zip file, I have 3 files. So, normally, I should have 3 times `entry trigger` but I only get 2 times.
So, the problem is not the uploadFile function (which does nothing actually, because not yet implemented). The problem is the event `entry` is triggered only 2 times instead of 3. In the end, I have the following log:
```
entry trigger
text.txt
entry trigger
WTxBc.jpg
WTxBc.jpg
```
But I don't understand why the event is not triggered on the last file. It works like a charm for the rest. Maybe I have misunderstood how unzipper works :/

**Comment by ZJONSSON** [comment]
Did you try running the two examples I shared above?   If both of the examples work but you are still having problems with your code, then just copy and paste your `uploadFile` function into a comment.

**Comment by georgesben** [comment]
The uploadFunction is the following:
```Javascript
function uploadFile(file){
   
};
```
I have said the function was not implemented. So, the problem cannot be this function. 
But ! An interesting thing is the `console.log()` shows 3 `entry trigger`. I have used the transform stream where we pipe the entry.

I don't understand why it works now. I don't think is normal that the event entry, used without that was triggered only 2 times. For me, maybe there are some configurations that block the event (it's just a supposition).
For me, it's a bug, because the expected behavior of the entry event for Unzipper is to be triggered for each file in the zip.
Furthermore, I don't understand why this hack work :/

**Comment by ZJONSSON** [comment]
But this empty function is exactly the problem.  The function would have to `consume` the stream in order for next entry to be emitted.  If the function is empty (or otherwise does not consume the entry stream) then `unzipper` is paused and no further entries are emitted due to backpressure.

Managing back-pressure correctly is a very important feature of `unzipper`.   Lets say you want to take the contents of 1TB zipfile and pipe it into a database.    Lets say for arguments sake that the upload process is very time consuming, and much slower than the unzip.   If your unzip would just keep unzipping no-matter-what and emitting entries without reservations, then the process would shortly run out of memory (as unzipped content sits in an ever-increasing buffer).   `unzipper` however uses a pull-stream structure to pull data through the unzipper only when needed, pausing when the uploader is busy - retaining a low memory footprint throughout.

The management of back-pressure is central to the node-core.   Here is a quick example:
```js
var file = fs.readFile('./testfile.txt');
file.on('end',function() {
  console.log('next entry');
});
```
The end event is never emitted and `next entry` never shown, as the file is never actually read.   The file-stream is simply paused indefinitely, unless you start consuming it, i.e. adding: `file.pipe(fs.createWriteStream('./testfile2.txt'))`.  etc.  Until then the stream is locked in `paused` state.

The official docs for [node streams](https://nodejs.org/api/stream.html#stream_three_states) show the following: 
> Calling `readable.pause()`, `readable.unpipe()`, or receiving "back pressure" will cause the `readable._readableState.flowing` to be set as `false`, temporarily halting the flowing of events but not halting the generation of data.

More reading material here:
[Streams explained](https://howtonode.org/streams-explained)
[node-streams-back-pressure](http://ey3ball.github.io/posts/2014/07/17/node-streams-back-pressure/)

**Comment by georgesben** [comment]
Ok, I understand now. I have to write the upload function to consume the stream ! 

Thank you very much for your help ! :smiley:

**Comment by ZJONSSON** [comment]
Glad this was helpful.  On the basis of this conversation I added a new method `.buffer` that buffers up the full contents of the entry and returns a Promise to the complete buffer.    This method is not the recommended way to consume a stream (as it retains the buffer in memory), but it provides an alternative to the stream-only approach.

see https://github.com/ZJONSSON/node-unzipper/pull/11
