### ISSUE TITLE
large zip extract in s3 with aws lambda in nodejs

### ISSUE THREAD

**Issue by Badamgarav** [ZJONSSON/node-unzipper#107]
### how to put entry to S3?
        s3.getObject({
        Bucket: srcBucket,
        Key: srcKey
       }).createReadStream()
        .on('error', function (err) {
            console.log('S3 get object err:: ', err);
        })
        .pipe(unzipper.Parse())
        .on('entry', function (entry) {
            var fileName = entry.path;
            var type = entry.type; // 'Directory' or 'File'
            var size = entry.size;
            if (fileName === "this IS the file I'm looking for") {
                entry.pipe(how to S3 putObject);
            } else {
                entry.autodrain();
            }
        });

**Comment by ZJONSSON** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

According to the aws docs the `Body` of the putObject can be a stream.
```js
s3.putObject({Bucket, Key, Body: entry})
```

**Comment by ZJONSSON** [comment]
Closing as this is not a specific issue relating to `node-unzipper`.  Feel free to add more comments below if you are still having issues and I'll try to help.
