### ISSUE TITLE
Error: invalid signature: 0x88b1f - can we add support?

### ISSUE THREAD

**Issue by karlbecker** [ZJONSSON/node-unzipper#108]
I have a file with a `.tsv.gz` file ending, but when I try to unzip it with unzipper, it fails with this error:

```
Error: invalid signature: 0x88b1f
    at ~/my_repo/node_modules/unzipper/lib/parse.js:62:26
...
```

Anyone have knowledge to be able to add support for the `0x88b1f` signature? 

I tried editing the parse.js file and having this treated the same as a file with a signature of if `0x04034b50`, but it only read part of the file, and not the entire file.

Thanks!

**Comment by ZJONSSON** [comment]
`unzipper` handles regular `zip` files (which are compilations of `gz` that includes a directory of the included files).  You should be able to decompress a straight up `.gz` file with the native `zlib.createGunzip()` (for streaming) or `zlib.gunzip(buffer[, options], callback)` for a buffer  (see https://nodejs.org/api/zlib.html)

**Comment by aubergene** [comment]
I've been getting this error and also #75 and #48 when trying to unzip a tar.gz. The file is being read directly from disk and it extracts fine using the OSX archive utility. One thing which perhaps might be causing an issue is this zip contains a lot of symlinks, unsure if that could cause problems with checking a signature.
