### ISSUE TITLE
unzipper.Extract() sometimes freez

### ISSUE THREAD

**Issue by dangear** [ZJONSSON/node-unzipper#111]
I use `unzipper` with `ftp` module:

```
c.get(ftp_file_path, function (err, stream) { //get file from ftp
  stream.pipe(unzipper.Extract({path: local_subfolder})).on('entry', (entry)=>{
    console.log(entry.path) //log files in zip archive
  }).on('error', (e)=>{
    console.log('Error: ', e);
  }).on('close', ()=>{})
    //work with unzipped folder
})
```

Sometimes `unzipper` freez. In logs I see just part of files in zip archive (example: 20 from 100). I try to catch errors but nothing. What can I do for catch errors or why unzipper freez.
Anytime work great but sometime it breaks.

**Comment by ZJONSSON** [comment]
I hope this has been resolved with #123.  Please reopen if issue persists
