### ISSUE TITLE
Does not extract if output dir is not in the root dir.

### ISSUE THREAD

**Issue by saurav-singh** [ZJONSSON/node-unzipper#113]
This works:
fs.createReadStream("public/icons/Add.zip").pipe(uzipper.Extract({**path:"icons**"}))

But this does not:
fs.createReadStream("public/icons/Add.zip").pipe(uzipper.Extract({path:"**public/icons**"}))

**Comment by ZJONSSON** [comment]
The extract uses [fstream](https://www.npmjs.com/package/fstream) for the extract file writes.  Fstream is very flexible and usually handles well directories that do not exists yet.   I tried your code locally and it works for me.   Can you clarify which OS you are running, node version and version of unzipper?

**Comment by ZJONSSON** [comment]
@saurav-singh  did you get any further clarity on this issue?
