### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by panther7** [ZJONSSON/node-unzipper#115]
Hi, is possible add support for smylinks? Thanks

**Comment by ZJONSSON** [comment]
Can you please clarify exactly what behavior you would be expecting?

**Comment by ZJONSSON** [comment]
Please reopen with a more detail description of exactly what the issue is and what behavior you expect.

**Comment by ngocdaothanh** [comment]
I think @panther7 is asking for symlink support inside zip files:
https://serverfault.com/questions/265675/how-can-i-zip-compress-a-symlink

For example, when you zip `node_modules` directory, it may look like this:

```
node_modules/.bin/
  acorn -> ../acorn/bin/acorn
  mkdirp -> ../mkdirp/bin/cmd.js
  rimraf -> ../rimraf/bin.js
  uuid -> ../uuid/bin/uuid
...
```

Currently, for `node_modules/.bin/acorn`, node-unzipper's `entry` event will be like this:

* `entry.type` is `'File'`.
* `entry.buffer()` gives the content `../acorn/bin/acorn`.

@ZJONSSON My suggestion is to set the type to `Symlink`.

**Comment by ZJONSSON** [comment]
Thanks for the clarification @ngocdaothanh - would you be willing to submit a PR?

**Comment by connor4312** [comment]
This should probably be reopened -- ran into this problem trying to unzip an folder containing an osx .app file.
