### ISSUE TITLE
Support CRX Package Format

### ISSUE THREAD

**Issue by silverwind** [ZJONSSON/node-unzipper#118]
Chrome extensions in CRX format are zips but with a special header that makes them incompatible with unzipper. Attempting to extract a CRX file like [this](https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP2-DYG6w-clYO36ra-A8YEKLtYTBzUlY8W7jQx8z-A6dR5ZhAgDlz8s-41VRN8nQuR9KDyuTsHY7CdJxogx_Lt1AMZSmuUxJOmfTwfh4LxK8PuA-2LMzUfJpQ/extension_19_5_18_1335.crx) one results in a `FILE_ENDED` error.

Details on the format are [here](http://www.adambarth.com/experimental/crx/docs/crx.html), would be great if support for this format could be added.

There is the [unzip-crx](https://github.com/peerigon/unzip-crx) module which handles the format, but I'm looking for something that can do in-memory extraction, like unzipper. I guess the function that strips this header could be easily ported to unzipper.

**Comment by ZJONSSON** [comment]
Providing support in the streaming version is easy, please see a quick implementation here: https://github.com/ZJONSSON/node-unzipper/commit/48428ba64781bd91a6ab7ed5a18ef57a549a9434

You can check it out by installing: `npm install zjonsson/node-unzipper#crx`

The `Open` methods would involve specifically opening up the start of the file to find out where the actual zip file starts and then adding this `startOffset` to all methods that read from the file.    If you use an open method with a Buffer you can manually find out where the zip file starts and create a new buffer that contains only the zipfile

**Comment by silverwind** [comment]
Thanks! I was specifically looking to use `Open.buffer`. Does that mean I have to manually find this `startOffset` when using `Open`? Can't it be detected there as well?

**Comment by ZJONSSON** [comment]
Yes absolutely.  You could do something like: 
```js
// with `buffer` as the buffered data
var signature = buffer.readUInt32LE(0);
if (signature === 0x34327243) {
  const baseHeaderLength = 4*4;
  var h = binary.parse(buffer)
    .word32lu('signature')
    .word32lu('version')
    .word32lu('pubKeyLength')
    .word32lu('signatureLength')
    .vars;

  buffer = buffer.slice(baseHeaderLength +  h.pubKeyLength + h.signatureLength);
}
var directory = await unzipper.Open.buffer(buffer);
```

I added this check to the `Open.buffer` method on the `crx` branch https://github.com/ZJONSSON/node-unzipper/commit/b9bd05d8646131dbd25f2b6f03b1f8507145d4b1

**Comment by silverwind** [comment]
Awesome, can confirm it working:

````js
const unzipper = require("unzipper");
const fetch = require("make-fetch-happen");

async function main() {
  const id = "hlepfoohegkhhmjieoechaddaejaokhf";
  const res = await fetch(`https://clients2.google.com/service/update2/crx?response=redirect&prodversion=74.0&x=id%3D${id}%26installsource%3Dondemand%26uc`);
  const buffer = await res.buffer();
  const dir = await unzipper.Open.buffer(buffer);
  console.log(dir.files.map(file => file.path));
}

main();
````

In case you're wondering about my use case: I'm pulling CSS files out of released chrome extensions, see [here](https://github.com/StylishThemes/GitHub-Dark/blob/f64e474e3ee572cfd1aba775de98966ad71b4d1d/tools/generate.js#L571). Once your patch is released, I can drop two dependencies and do it all in-memory. :)
