### ISSUE TITLE
Extract and Parse don't work

### ISSUE THREAD

**Issue by NAlexandrov** [ZJONSSON/node-unzipper#122]
I have an archive: data.zip (615 files) and the next script:

```javascript
const fs = require('fs');
const path = require('path');
const unzipper = require('unzipper');

fs.createReadStream('./data.zip')
  .pipe(unzipper.Extract({ path: path.join(__dirname, 'data') }))
  .promise()
  .then(() => console.log('ok'));
```

This script exits without printing "ok" and file data/db_dump/14076.dat.gz has 0 bytes and `find ./data -type f | wc -l` prints 334 files

If I change script:
```javascript
const fs = require('fs');
const unzipper = require('unzipper');
let filesCount = 0;

fs.createReadStream('./data.zip')
  .pipe(unzipper.Parse()).on('entry', (entry) => {
    filesCount++;
    console.log(filesCount , entry);
    entry.autodrain();
  });
```
In the console I see the last entry #334 db_dump/14076.dat.gz before exit.

And if I change script:
```javascript
const unzipper = require('unzipper');

unzipper.Open.file('./data.zip')
  .then(dir => console.log(dir.files.length));
```
I see the count of files = 615 as expected.

Why Extract or Parse can not read all files from archive instead of unzipper.Open.file? It is bug?

**Comment by ZJONSSON** [comment]
@NAlexandrov thanks for the report - I do believe I caught an annoying bug where the intermediate buffer is exactly the same length as the `eof` we are looking for and a callback for more stuff is not called.   This should be fixed in the newly published version (`+ unzipper@0.9.14`).  Can you please verify on your end that the issue is resolved?

**Comment by NAlexandrov** [comment]
All works as expected. Thank you.

**Comment by ZJONSSON** [comment]
Excellent, thank you for verifying!
