### ISSUE TITLE
0.8 -> 0.9 migration path?

### ISSUE THREAD

**Issue by catamphetamine** [ZJONSSON/node-unzipper#130]
Nothing on the :Releases" tab.
No "Changelog" file.
What's the upgrade path from 0.8 to 0.9?

**Comment by ZJONSSON** [comment]
Good suggestion on communicating through the Releases tab. 

The api itself has been mostly stable and fully backwards compatible for a long time.  The reason for a minor bump from 0.8 - 0.9 was the inclusion of a polyfill for node version < 8:  https://github.com/ZJONSSON/node-unzipper/commit/a3e581404f86596af53ccd2c62e3467b97d54103

**Comment by catamphetamine** [comment]
I see, ok.
