### ISSUE TITLE
error with Extract promise

### ISSUE THREAD

**Issue by Mosby-zhou** [ZJONSSON/node-unzipper#136]
const unzipper = require('unzipper');
const fs = require('fs');

(async () => {
  await fs.createReadStream('./test-dir.zip')
    .pipe(unzipper.Extract({ path: './tmpdir', }))
    .promise();
})().then(r => process.exit(0));

---------------------------
at v0.10.0 this code get a empty dir
at v0.9.15 get dir with files

**Comment by Mosby-zhou** [comment]
https://github.com/ZJONSSON/node-unzipper/blob/f162a8590544bef8806668729f4e82e4d912398c/lib/extract.js#L49
it should be 
```
      extract.on('end', resolve);
```

**Comment by ZJONSSON** [comment]
Good catch @Mosby-zhou - do you want to submit a PR?

**Comment by ZJONSSON** [comment]
published as `+ unzipper@0.10.1`
