### ISSUE TITLE
Versioning is confusing

### ISSUE THREAD

**Issue by polys** [ZJONSSON/node-unzipper#139]
Version `0.10.1` appears to be the latest version on npm but a corresponding release on GitHub doesn't exist.

On GitHub, version `0.10.10` appears to be the latest but the tag is `v0.10.0`.

It's unclear which version of the code corresponds to which package on npm.

**Comment by ZJONSSON** [comment]
Thanks @polys for raising the issue - if you look at `package.json` you see version `0.10.1` on master which matches the version on npm.     If you are looking at the releases tab then the `0.10.10` is a typo, which has now been fixed (the latest minor release is `0.10.0`).   Please reopen if you have further issues with versioning.

**Comment by polys** [comment]
Great, many thanks!
