### ISSUE TITLE
Stream ends prematurely 

### ISSUE THREAD

**Issue by georgesben** [ZJONSSON/node-unzipper#14]
Hi !

Sorry to trouble you, but I have a little problem with my stream. Actually, I have an application which can manage image uploads. The images can also be in a zip file. In the two cases, I need managing the big pictures (max 1000*1000). So, I use the module sharp for that (which can use stream). Finally, I upload files on S3. To resume:

`Image file => sharp => S3`

`Zip file => unzipper => sharp => S3`

In the case of simple picture files, it works. But for the zip file, I have the error `Write After End`. If I have well understood, this error happens if I try to write after closing a stream.
This is my buggy code:
```javascript
function uploadZip(filepath, idParty){
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            let filename = entry.path;
            if (isImage(filename)){
                console.log(filename);
                uploadFile(imageStream, filename, idParty).then(function(result){
                        entry.autodrain();
                    },function(err){
                        entry.autodrain();
                    });
            }
            else {
                entry.autodrain();
            }
        });
};
```

I don't understand what I'm doing wrong. With the promise, I have tried to force closing the stream only after the promise finished. But it doesn't work.

I have tried with the buffer method:
```javascript
function uploadZip(filepath, idParty){
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            let filename = entry.path;
            if (isImage(filename)){
                console.log(filename);
                entry.buffer().then((buf) => uploadFile(buf, filename, idParty));
            }
            else {
                entry.autodrain();
            }
        });
};
```

This approach works. But you have said the recommended strategy is the stream approach, so I really want to try with streams. Can you help me, please ?

Thank you very much :)

**Comment by ZJONSSON** [comment]
The `autodrain` is used to consume entries you are not consuming,   Essentially it takes the entry and pipes it into a temporary stream that discards the information.   This is required as the zipfile is read lazily and you can't move to the next entry unless the previous one has been read (consumed).

I think the problem in the first example is that you are trying to consume (i.e. autodrain) the stream after its already been closed (assuming uploadFile is resolved when the stream is complete).

My initial suggestion would be to modify the entry callback to:
```js
function(entry) {
  let filename = entry.path;
  if (isImage(filename)) {
    console.log(filename);
    uploadFile(imageStream, filename, idParty)
  }
  else {
    entry.autodrain();
  }
}
```

**Comment by georgesben** [comment]
I have forgotten to say that I use the entry as a stream (sorry, I have rebuilt my buggy function after I have used the buffer approach). So I have tried this:

```javascript
function uploadZip(filepath, idParty){
    fs.createReadStream(filepath)
        .pipe(unzipper.Parse())
        .on('entry', function(entry){
            let filename = entry.path;
            if (isImage(filename)) {
                console.log(filename);
                let imageStream = entry.pipe(imageManager.manageImage);
                uploadFile(imageStream, filename, idParty)
            }
            else {
                entry.autodrain();
            }
        });
};
```
And I have this error:
```
Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Sharp.Writable.write (_stream_writable.js:217:5)
    at PassThrough.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at PassThrough.Readable.push (_stream_readable.js:134:10)
    at PassThrough.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:77:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at PassThrough._transform (_stream_passthrough.js:21:3)
    at PassThrough.Transform._read (_stream_transform.js:167:10)
    at PassThrough.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at PassThrough.Writable.write (_stream_writable.js:220:11)
```

**Comment by ZJONSSON** [comment]
it seems like this comes from the consumer of the stream (i.e. the imagemanager).  
Is it possible that you need to create a new imageManager for each stream (i.e. if you try to pass another entry into a stream you have already written a previous image to, then the receiving stream has already `end`ed and you will get `write after end` error

**Comment by ZJONSSON** [comment]
Since the `module.exports` is not a function it will always be the same stream when you reference it.   If you modify the code as follows it should probably work:
```js
exports.manageImage = function() {
  return sharp().resize(widthMax, heightMax).max();
}
```

and 
```js
 let imageStream = entry.pipe(imageManager.manageImage());
```

Here is a benchmark example that streams end-to-end:   http => unzip => sharp => file
```js
var request = require('request');
var unzipper = require('unzipper');
var sharp = require('sharp');
var fs = require('fs');

request({
  url: 'http://valuestockphoto.com/freehighresimages/sample_cart.zip',
  encoding : null
})
.pipe(unzipper.Parse())
.on('entry', entry => {
  entry.pipe(sharp().resize(100, 100).max())
    .pipe(fs.createWriteStream(entry.path));
});
```

**Comment by georgesben** [comment]
It works perfectly !

You are my hero ! =D
