### ISSUE TITLE
uncaught FILE_ENDED error on windows (linux works fine)

### ISSUE THREAD

**Issue by alvi1987** [ZJONSSON/node-unzipper#143]
When I am using unzipper to unzip a downloaded it works fine in linux dev environment, throws following error in windows packaged app packaged with electron packager. the zip file has been created on a linux machine.

```
Uncaught Exception:
Error: FILE_ENDED
   at Parse.pull(F:\project\path\resources\app\node_modules\unzipper\lib\PullSteam.js:80:28
   at emitOne(events.js:96:13)
   at Parse.emit(events.js:188:7)
   at Parse.<anonymous>
```

**Comment by ZJONSSON** [comment]
Would love to debug this, but to do that I would need a link to the file, either here or email: ziggy.jonsson.nyc@gmail.com

**Comment by ZJONSSON** [comment]
@alvi1987 did you find out the problem or do you want me to help out?

**Comment by ZJONSSON** [comment]
@alvi1987 closing this - please reopen if this is still a problem and you can share more detail
