### ISSUE TITLE
can not unzip an empty folder

### ISSUE THREAD

**Issue by wseven7677** [ZJONSSON/node-unzipper#144]
hi,
i got a zip called 111.zip
it was zipped from a folder called 111.
i would unzip '111.zip'. I don't know there are things in the folder or not.

so when the folder called 111 has nothing in it, i got nothing  after unzip `111.zip`, which was supposed to be an empt folder called 111.

please help~

**Comment by ZJONSSON** [comment]
Can you please clarify:   Does the zip file only contain an empty folder called 111?    And you want the unzipper to just create this empty folder?

**Comment by wseven7677** [comment]
> Can you please clarify: Does the zip file only contain an empty folder called 111? And you want the unzipper to just create this empty folder?
@ZJONSSON 
yes, the zip file only contain an empty folder called 111, and  when i upzip it with unzipper, i got nothing, which i expect it to be an empty folder.

i use unzipper for lots of zip files called 111.zip, some of them contain a folder with files in it while others just contain an empty folder. maybe  i can handle it as a special case, but i prefer to get just an empty folder.

**Comment by ZJONSSON** [comment]
Good point - the expected behavior should be to extract exactly what is in the zipfile, empty folders included.

**Comment by wseven7677** [comment]
@ZJONSSON 
🎉🎉🎉, so how long it will take to experience this feature?

i 'd like to update my schedule depending on the time when i can use this feature~

**Comment by flokol120** [comment]
I just stumbled along this behavior too. I'd be very pleased if this would be added soon.

**Comment by Aarbel** [comment]
@ZJONSSON same issue here, when will you fix that ? 

our users drop zip files with some empty folders, like pre formatted trees. Would be great to be able to detect / create empty folders when unziping it.

**Comment by italogustavoborba** [comment]
Hi, any solution? I need keep empty file

**Comment by qq253498229** [comment]
I have the same requirement. May I ask if there has been any progress on this?

**Comment by ZJONSSON** [comment]
This has now been resolved by replacing `fstream` with `fs-extra` https://github.com/ZJONSSON/node-unzipper/pull/318/files#diff-ad67f830ededacce71edff0de408c01f6d287c3bb7c95f64cc5c3b0ae7494bdcR30

Empty directories are now explicitly extracted (see [test](https://github.com/ZJONSSON/node-unzipper/blob/master/test/compressed.js#L55-L68))

Published as `unzipper@0.12.1`
