### ISSUE TITLE
Zip64 support?

### ISSUE THREAD

**Issue by jthomas** [ZJONSSON/node-unzipper#145]
I'm attempting to use this library with a huge zip file on S3 (128GB). I was testing with a small zip file and my script was working. Once I moved to the larger archive as the input file, the file listing returned seem incorrect. 

Digging into this, the source file is now Zip64 format. The EOCD directory offset for Zip64 files is set to be `0xffffffff`, which means the CD record is read from that address and it parses incorrect values.

Looking at other zip implementations, Go lang has an idea of how to handle this stuff: 
https://github.com/golang/go/blob/539ff607a70bb6f7f12b1bca6b365ab0af448fcf/src/archive/zip/reader.go#L503-L511

Do you know anymore about what it would take to support this file format as well?

BTW - thanks for this library - it worked great for normal zip files (< 4GB).

**Comment by ZJONSSON** [comment]
Thanks @jthomas this is an excellent feature request.  Let me know if you want to take a stab at a PR?  Otherwise I will look at this soon

**Comment by ZJONSSON** [comment]
For reference, here is a [test file](https://github.com/golang/go/blob/539ff607a70bb6f7f12b1bca6b365ab0af448fcf/src/archive/zip/testdata/zip64.zip) from the go library

**Comment by jthomas** [comment]
@ZJONSSON I'm going to see if I can make this work. Will let you know how I get on...

**Comment by jthomas** [comment]
Think I've got something work 💯. Will finish up the code & tests and open a PR tomorrow...
