### ISSUE TITLE
EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by rhtpandeyIN** [ZJONSSON/node-unzipper#15]
Hi, we are facing few problem while migrating the node-unzip api to node-unzipper apis. earlier we were using node-unzip api for extract and parsing purpose, but now we decided to use unzipper instead of unzip.
following are the error messages we are getting while installing or unzipping the zip file.

npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'E:\1\node_modules\repo'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'E:\1\node_modules\repo']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'E:\\1\\node_modules\\repo' }

following are the code samples which we were using earlier and now, please suggest me what is best way to use unzipper api for my purpose.

**earlier:  with node-unzip**

var ZIP_FILE= path.resolve(CURRENT_DIR, 'build.zip');
            readStream = fs.createReadStream(ZIP_FILE);
            writeStream = fstream.Writer(CURRENT_DIR);

            readStream
              .pipe(unzip.Parse())
              .pipe(writeStream).on("unpipe", function () {
                fs.unlinkSync(ZIP_FILE);

                var FILE1 = path.resolve(CURRENT_DIR, 
                              'build\\Release\\file1.node');
                var FILE2 = path.resolve(CURRENT_DIR,
                              'build\\Release\\file2.node');
                var FILE3 = path.resolve(CURRENT_DIR,
                              'build\\Release\\file3.node');
               
                fs.exists(FILE1 , function() {
                  if(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) {
                      fs.renameSync(FILE2 , FILE1);
                      fs.unlinkSync(FILE3);             
                  } else if(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) {
                      fs.renameSync(FILE3 , FILE1);
                      fs.unlinkSync(FILE2);             
                  } else {
                      fs.unlinkSync(FILE2 );
                      fs.unlinkSync(FILE3 );             
                  }
                });
            });

**Now with node-unzipper**

var ZIP_FILE= path.resolve(CURRENT_DIR, 'build.zip');
            readStream = fs.createReadStream(ZIP_FILE);

            var extractBuildZip = readStream.pipe(unzipper.Extract({path: CURRENT_DIR}));
		extractBuildZip.on('close', function(){
			fs.unlinkSync(ZIP_FILE);
			var FILE1= path.resolve(CURRENT_DIR,
							 'build\\Release\\file1.node');
			var FILE2= path.resolve(CURRENT_DIR,
							     'build\\Release\\file2.node');
			var FILE3= path.resolve(CURRENT_DIR,
							     'build\\Release\\file3.node');
			
			fs.exists(FILE1, function() {
				if(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) {
					fs.renameSync(FILE2, FILE1);
					fs.unlinkSync(FILE3);	
				} else if(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) {
					fs.renameSync(FILE3, FILE1);
					fs.unlinkSync(FILE2);
				} else {
					fs.unlinkSync(FILE2);
					fs.unlinkSync(FILE3);
				}
			});
			extractBuildZip.on('err', function(){
				console.log(err);
			});
		});

but now it started giving error on fs.renameSync or fs.unlinkSync calls, after restarting windows it works fine but then again if I do install, it throws the same error.

**Comment by ZJONSSON** [comment]
Thanks for the report.  

* Can you clarify what E:\node_modules\repo is?  At first sight this looks to be something outside of the unzipper, as one would expect to see build\Relase\...  in the error messages.
* if this error comes up when you are installing, can you try doing just `npm install unzipper` to see if you get errors?  If not then the error comes from something else.

There is a possible race condition in `unzipper.Extract` as the `close` and `finish` events are emitted when the file has been read, but the output streams might not have finished yet.  I'll see if I can get a patch in, but again I'm not sure if this is the issue.

Alternatively you might explore only unzipping the file you need in the stream itself, i.e. checking each entry in the zip and save the correct file, while autodraining the others.  This should be more efficient and faster.  Something like:
```js
var filename =(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) && 'file1.node'  || 
              (Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) && 'file2.node'  || 
              'file3.node';

readStream.pipe(unzipper.Parse())
  .pipe(stream.Transform({
    transform: (entry, encoding, cb) => {
      if (entry.path.indexOf(filename) !== -1) {
        entry.pipe(fs.createWriteStream(path.resolve(CURRENT_DIR,'build\\Release\\file1.node')))
          .on('error',e => cb(e))
          .on('finish',cb);
       } else {
         entry.autodrain();
       }
    }
  }))
  .on('error',e => console.log('error',e))
  .on('finish',() => console.log('done'))
```

or using `etl` library which allows for easy context switch to promises when a stream finishes.

```js
var filename =(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) && 'file1.node'  || 
              (Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) && 'file2.node'  || 
              'file3.node';

readStream.pipe(unzipper.Parse())
  .pipe(etl.map(entry => {
    if (entry.path.indexOf(filename) !== -1)
      return entry.pipe(etl.toFile(path.resolve(CURRENT_DIR,'build\\Release\\file1.node')))
        .promise();
    else
      entry.autodrain();
  }))
  .promise()
  .then(() => console.log('done'),e => console.log('error',e));
```

(code not verified)

**Comment by ZJONSSON** [comment]
Even simpler, you could also use `unzipper.parseOne(regex)` which pipes the first matching file (or first file if regex is blank) and pipes it down.

So you could do:

```js
var filename =(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) && 'file1.node'  || 
              (Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) && 'file2.node'  || 
              'file3.node';

readStream
  .pipe(unzipper.ParseOne(filename))
  .pipe(fs.createWriteStream(path.resolve(CURRENT_DIR,'build\\Release\\file1.node')))
  .on('error', e => console.log('error',e))
  .on('finish', () => console.log('done'));
```

**Comment by rhtpandeyIN** [comment]
Thanks for the help @ZJONSSON , 

Can you clarify what E:\node_modules\repo is? At first sight this looks to be something outside of the unzipper, as one would expect to see build\Relase... in the error messages.

and yes it is outside of the unzipper, here "repo" is our own module in which we are using unzipper api to extract few zip files. build.zip is the zipped file inside which build\Release folder exists.

I will try as per your instructions, thanks again for the quick help.

**Comment by rhtpandeyIN** [comment]
Hi I tried the same way you suggest, but It is still throwing error,
**When I am using ParseOne api:**

var filename =(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) && 'file1.node'  || 
              (Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) && 'file2.node'  || 
              'file3.node';
console.log('filename is 1: ',filename);
readStream = fs.createReadStream(BUILD_FILE);

readStream
  .pipe(unzipper.ParseOne(filename))
  .pipe(fs.createWriteStream(path.resolve(CURRENT_DIR,'build\\Release\\file1.node')))
  .on('error', e => console.log('error',e))
  .on('finish', () => console.log('done'));

the following error I am getting:

> node installer/driverInstall.js

filename is 1:  E:\2\test\node_modules\repo\build\Release\file3.node
error { [Error: ENOENT: no such file or directory, open 'E:\2\test\node_modules\repo\build\Release\file1.node']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\2\\test\\node_modules\\repo\\build\\Release\\file1.node' }


**and when I am using unzipper.Parse() with stream.Transform()**

var filename =(Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 0.12) && 'file1.node'  || 
              (Number(process.version.match(/^v(\d+\.\d+)/)[1]) < 4.0) && 'file2.node'  || 
              'file3.node';
console.log('filename is 1: ',filename);
readStream = fs.createReadStream(BUILD_FILE);

readStream
              .pipe(unzipper.Parse())
	          .pipe(stream.Transform({
	          transform: (entry, encoding, cb) => {
				  console.log('filename is 2: ',filename);
				  console.log('entry is 2: ',entry);
		      if(entry.path.indexOf(filename) !== -1) {
				  console.log('filename is 3: ',filename);
		          entry.pipe(fs.createWriteStream(path.resolve(CURRENT_DIR,'build\\Release\\file1.node')))
			  .on('error',e => cb(e))
			  .on('finish',cb);
		        }else{
			    entry.autodrain();
		        }
		    }
		}))
		.on('error',e => console.log('error',e))
		.on('finish',() => console.log('done'));


and the following error I am getting:

> node installer/driverInstall.js
filename is 1:  E:\2\test\node_modules\repo\build\Release\file3.node
error [TypeError: Invalid non-string/buffer chunk]


^^^ I guess in second case control not even going inside the stream.Transform.
or I am doing something wrong please suggest. Thanks

**Comment by ZJONSSON** [comment]
First case: (parseOne)
The  directory possibly doesn't exist in this case (previously it was generated by the extract).  You can either simply write the file into a directory that you know exists, create the `CURRENT_DIR,'build\\Release\\` in beforehand or use `.pipe(fstream.Write({path:path.resolve(CURRENT_DIR,'build\Release\file1.node')}))` (which should create the directory for you)

Second case: (Transform)
I forgot to put `objectMode: true` into the options of the transform.  I have edited the example to reflect.

**Comment by rhtpandeyIN** [comment]
I used the Transform code and I am always getting "-1" while checking the if condition.
I double checked the same file exist in the build\Release directory inside zipped file. but still it is not able to read that.

readStream
              .pipe(unzipper.Parse())
	          .pipe(stream.Transform({
			    objectMode: true, 
	            transform: (entry, encoding, cb) => {
				  console.log('filename is 2: ',filename);
				  console.log('entry.path.indexOf(filename) = ',entry.path.indexOf(filename));
				  console.log('entry.path = ', entry.path);
				  
		          if(entry.path.indexOf(filename) !== -1) {
		          entry.pipe(fs.createWriteStream(path.resolve(CURRENT_DIR,'build\\Release\\file1.node')))
			        .on('error',e => cb(e))
			        .on('finish',cb);
		          }else{
			       entry.autodrain();
		          }
		        }
		    }))
		    .on('error',e => console.log('error',e))
		    .on('finish',() => console.log('done'));

**here is the output for that:**

filename is 2:  E:\2\unzippertest\node_modules\repo\build\Release\file2.node
entry.path.indexOf(filename) =  -1
entry.path =  build/

**Comment by rhtpandeyIN** [comment]
and (parseOne) is able to create directory and extract the node file into build\Release directory, but when I am using the node file for execution of test cases or application, it throws error that "invalid win 32 application", it seems there is just a same name file exists not the exact node binary. 
I have used code like this:
```
readStream
            .pipe(unzipper.ParseOne(filename))
			.pipe(fstream.Writer({path:path.resolve(CURRENT_DIR,'build\\Release\\odbc_bindings.node')}))  
            .on('error', e => console.log('error',e))
            .on('finish', () => console.log('done'));
```

**Comment by rhtpandeyIN** [comment]
hurrah! finally it worked out.... :+1: 
Thanks for your support and help.

readStream
			.pipe(unzipper.Parse())
			.on('entry', function (entry) {
				if(entry.path === filename){
				   entry.pipe(fstream.Writer(ODBC_BINDINGS));
				}
				else{
			       entry.autodrain();
		        }
			})
			.on('error', e => console.log('error',e))
			.on('finish', () => fs.unlinkSync(BUILD_FILE));

**Comment by ZJONSSON** [comment]
Thanks again for the report.  This should not be this difficult so I will patch the `Extract` to only finish when the files have been written and closed. 

The bug you saw previously (0Kb file) indicates that no file was passed on from the ParseOne.   The `filename` parameter should be a regex that matches the `entry.path`, maybe there was a discrepancy.

Glad it finally worked!
