### ISSUE TITLE
Is it possible to decrypt (password-protected) files using stream input?

### ISSUE THREAD

**Issue by adrielpdeguzman** [ZJONSSON/node-unzipper#153]
I've seen that it's possible when using ```Open (Open.Buffer)```. How about if we are just piping the zip file from a stream? #

**Comment by benplain** [comment]
@adrielpdeguzman, what sort of stream are you referring to?
If you are referring to a input file stream, then I have managed to do this using `FileReader`

```
var reader = new FileReader()

reader.onload = async (e) => {
    let arrayBuffer = e.target.result
    const directory = await unzipper.Open.buffer(Buffer.from(arrayBuffer))
    ....
}

reader.readAsArrayBuffer(event.target.files[0])
```
