### ISSUE TITLE
Error unzipping in AWS Lambda

### ISSUE THREAD

**Issue by josematamoros** [ZJONSSON/node-unzipper#154]
I'm trying to decompress a ZIP file in a AWS Lambda function. I'm working with the Serverless Framework.

The unzipper library works fine locally. I have the following code:

```
  return new Promise((resolve, reject) => {
    fs.createReadStream(zipFile)
      .pipe(unzipper.Extract({ path: dstDir }))
      .on('close', () => {
        resolve();
      })
      .on('error', (e) => {
        reject(e);
      });
  });
}
```

It's just a function that returns a promise. The promise is resolved when the file is completely extracted ('close' event). On any error ('error' event), the promise is rejected.

As I mentioned before, when I execute the function locally (sls offline start), it seems to work properly. But when I deploy the function in AWS, I get an error:

```
 "name": "Error",
        "message": "FILE_ENDED",
        "stack": "Error: FILE_ENDED\n    at Parse.pull (/var/task/node_modules/unzipper/lib/PullStream.js:83:28)\n    at Parse.emit (events.js:198:13)\n    at Parse.EventEmitter.emit (domain.js:448:20)\n    at Parse.<anonymous> (/var/task/node_modules/unzipper/lib/PullStream.js:20:10)\n    at Parse.emit (events.js:203:15)\n    at Parse.EventEmitter.emit (domain.js:448:20)\n    at finishMaybe (_stream_writable.js:646:14)\n    at endWritable (_stream_writable.js:663:3)\n    at Parse.Writable.end (_stream_writable.js:594:5)\n    at DuplexWrapper.<anonymous> (/var/task/node_modules/duplexer2/index.js:29:14)\n    at Object.onceWrapper (events.js:286:20)\n    at DuplexWrapper.emit (events.js:203:15)\n    at DuplexWrapper.EventEmitter.emit (domain.js:448:20)\n    at finishMaybe (/var/task/node_modules/readable-stream/lib/_stream_writable.js:630:14)\n    at endWritable (/var/task/node_modules/readable-stream/lib/_stream_writable.js:638:3)\n    at DuplexWrapper.Writable.end (/var/task/node_modules/readable-stream/lib/_stream_writable.js:594:41)"
```

Do you known any limitation concerning the execution of unzipper in lambda functions?

Thank you

**Comment by ZJONSSON** [comment]
`FILE_ENDED` is usually an indication that it is not a zip file, or corrupted.    For example if it's a binary file that is base64 encoded then doing unzipper.Extract will fail with a `FILE_ENDED`  (meaning it continued searching for local headers, didn't find any and then reached the end).

How do you get the zipfile itself to the lambda?   If it is through the payload to the function itself you probably have to base64 encode when you call and base64 decode before unzip (and in that case you can just unzip the buffer).    If the file comes from an outbound request made from the lambda (such as http request) you could try to pipe the request directly into the unzipper without saving to disk first etc.

Let me know how it goes

**Comment by pavelloz** [comment]
I believe its not lambda or unzippers fault, as i just finished implementing unzipping on lambda using unzipper after couple of days of banging my head against the wall using different library (node-unzip-2).

**Comment by ZJONSSON** [comment]
Thank you @pavelloz - loved the benchmarks!!
