### ISSUE TITLE
Same issue as Unzip on latest node and NVM

### ISSUE THREAD

**Issue by Killa4** [ZJONSSON/node-unzipper#161]
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined

**Comment by Killa4** [comment]
Had to revert to v10.16.0 for it to work

**Comment by ZJONSSON** [comment]
Thanks @Killa4 Can you share more detail:
* verify that you are using the latest version of unzipper (0.10.5)
* which node version you were running
* a stacktrace with the error above?

**Comment by ZJONSSON** [comment]
For reference here are the unit test results on node 13 for the latest version of unzipper:
https://travis-ci.org/ZJONSSON/node-unzipper/jobs/623483742

**Comment by ZJONSSON** [comment]
Closing this as the tests are green for node 12 & node 13.   @Killa4 If you still think this is an outstanding issue with unzipper, please reopen the ticket with more detail.
