### ISSUE TITLE
Not working with NodeJS 13.6

### ISSUE THREAD

**Issue by albertodiazdorado** [ZJONSSON/node-unzipper#168]
I just upgraded my NodeJS version and my simple snippet does not work any longer:

```
const zipPath = path.join(__dirname, 'a.zip');
const dirPath = __dirname
fs.createReadStream(zipPath).pipe(unzipper.Extract({ path: dirPath }))
```
It fails silently. No error message, no nothing. There is just no unzipped folder after the execution.

If I downgrade via `nvm use 10` and run the snippet again, then it works like a charm, like it always did.

**Comment by ZJONSSON** [comment]
published as `+ unzipper@0.10.7`
