### ISSUE TITLE
How to make sure the file was written to disk when using `ParseOne`?

### ISSUE THREAD

**Issue by skorunka** [ZJONSSON/node-unzipper#177]
Hello,
I got this simple code:
```
		fs
			.createReadStream(zipFile)
			.pipe(unzipper.ParseOne(/api\.json/gm))
			.pipe(fs.createWriteStream(toFile));
```

It seems the code is not blocking as if I immediately try to read the file, I got empty result.

I tried `await fs....` with no success.

Any idea how to make sure, the file is written to disk before the last pipe is finished?

Thanks.

**Comment by ZJONSSON** [comment]
The `fs.createWriteStream()` emits a `finished` event when the file has been written to disk.  You can wrap it in a promise like this

```js
await new Promise( (resolve, reject) => fs
  .createReadStream(zipFile)
  .on('error',reject)
  .pipe(unzipper.ParseOne(/api\.json/gm))
  .on('error',reject)
  .pipe(fs.createWriteStream(toFile))
  .on('error',reject)
  .on('finished',resolve)  
);
```

Errors are not propagated in streams so you need to check for the error event for each of the transforms.

The `ParseOne` method has to read though the entire zip file.   You might want to consider the `Open` method to only read the file you are interested in from the zip file.

Hope this work out.  Please let me know if you have any other issues

**Comment by skorunka** [comment]
@ZJONSSON thanks for your answer, now Im facing a problem like it seems the `resolve()` function is not executed. Here is my function:

```
	private async unzipApiSpec(zipFile: string, toFile: string, apiName: string) {
		this.log(`Unziping ...`, apiName);
		this.log(` - file: ${chalk.whiteBright(zipFile)}`, apiName);
		this.log(` - to: ${chalk.whiteBright(toFile)}`, apiName);

		await new Promise((resolve, reject) =>
			fs
				.createReadStream(zipFile)
				.on('error', reject)
				.pipe(unzipper.ParseOne(/api\.json/gm))
				.on('error', reject)
				.pipe(fs.createWriteStream(toFile))
				.on('error', reject)
				.on('finished', resolve)
		);

		rimraf.sync(zipFile);
		this.success('Json spec unzipped.', apiName);
	}
```
 The file is correctly extracted but the `rimraf` and success log message is not executed.

I call the function like `await this.unzipApiSpec(zipFile, api.sourceFile, api.name);`.

I might be missing some async/await knowledge here, but can't figure what it is :(.

**Comment by ZJONSSON** [comment]
Ah sorry - just realized the event you are waiting on should be `finish` not `finished` - I corrected my example above.

**Comment by skorunka** [comment]
Right, that make it working! :) Cheers.
