### ISSUE TITLE
Any example of streaming s3 zip file?

### ISSUE THREAD

**Issue by multiaki** [ZJONSSON/node-unzipper#183]
I am trying to unzip a file to the same S3 folder.
Here is my code 

` S3
      .getObject({ Bucket: event.bucket, Key: event.key })
      .createReadStream()
      .pipe(unzipper.Parse({ forceStream: true }))
      .pipe(uploadFromStream(bucket, key))
`
UploadFromStream function does this:
`
function uploadFromStream(Bucket, Key) {
  let pass = new stream.PassThrough();
  let params = { Bucket, Key, Body: pass };
  s3Client.upload(params, function(err, data) {
    console.log(err, data);
  });
  return pass;
}
`

Here is my error:
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object

My pass: readable state 
{
  "objectMode": false,
  "highWaterMark": 16384,
  "buffer": {
    "head": null,
    "tail": null,
    "length": 0
  },
  "length": 0,
  "pipes": null,
  "pipesCount": 0,
  "flowing": null,
  "ended": false,
  "endEmitted": false,
  "reading": false,
  "sync": false,
  "needReadable": false,
  "emittedReadable": false,
  "readableListening": false,
  "resumeScheduled": false,
  "paused": true,
  "emitClose": true,
  "autoDestroy": false,
  "destroyed": false,
  "defaultEncoding": "utf8",
  "awaitDrain": 0,
  "readingMore": false,
  "decoder": null,
  "encoding": null
}

it looks like the pass value is empty.

Could you help with the problem please. Any suggestion regarding piping unzipped file to S3 would be great.

Thanks

**Comment by ZJONSSON** [comment]
The unzipper.Parse() returns a stream of entry-objects where each entry describes and provides access to the content of the unzipped file.       Since it's a stream of objects you can't just pipe it to s3.

If you just need one file from the zip file you can use the `parseOne()` method which returns a stream of the content of the first matching file (you can put regex as an argument)

So this should work:
```js
const body = S3.getObject({ Bucket: event.bucket, Key: event.key }) 
  .createReadStream()
   .pipe(unzipper.ParseOne())
  
await s3Client.upload({Bucket, Key, Body}).promise();   // Body can be a stream here
``` 


If you want to push all the individual files to s3 you have to call the `stream()` method of each entry and pipe it to a separate s3 file.     For example, using async iterators:

```js
const zip = s3.getObject({ Bucket: event.bucket, Key: event.key })
   .createReadStream()
  .pipe(unzipper.Parse({forceStream: true}));

for await (const entry of zip) {
  const Bucket = 'xxxxx';
  const Key = `/prefix/${entry.path}`;
  const Body = entry.stream();
  await s3Client.upload({Bucket, Key, Body}).promise()
}
```

**Comment by multiaki** [comment]
@ZJONSSON Thank you very much. I understood my mistake. ParseOne streams one file contents, without waiting for the entire file being downloaded.
I have one clarification. Let's say I  have 5gb zip file. I need to:
- stream one file from s3
- unzip streamed chunk/buffer locally
- stream the chuck/buffer back to s3

By streaming, I mean, get a part of the zip file and not the entire file. I am clarifying it because, I might be confusing the streaming method. No saving or buffering except the current streamed data. No previous data is saved locally or in the memory. 5gb is too much for an AWS Lamba function to keep in memory.

**I have a code that works fine. But I need some clarification. I appreciate if you could take a look and give your expert thoughts.**

```
const AWS = require("aws-sdk");
const unzipper = require("unzipper");

const filePath = "newfile.csv";
const bucketName = "aws-zipfolder";
const key = "newfile.csv.zip";

let s3 = new AWS.S3();

let index = 0;
function streamToS3(body) {
  console.log(index++);
  return s3.upload({ Bucket: bucketName, Key: filePath, Body: body }).promise();
}

const downloadFile = async (filePath, bucketName, key) => {
  const params = {
    Bucket: bucketName,
    Key: key
  };
  const body = s3
    .getObject(params)
    .createReadStream()
    .on("error", e => {
      console.log(e);
    })
    .pipe(unzipper.ParseOne({ forceStream: true }))
    .on("end", () => {
      console.log("end");
    });

  return streamToS3(body);
};

downloadFile(filePath, bucketName, key).then(
  () => console.log("done"),
  e => console.log("error", e)
);
```

I want to understand whether the data is streamed to S3 without buffering entire file locally:

My script below is the one that uploads to S3. It seems to be triggered once, instead of multiple times. Here is the code:
```
let index = 0;
function streamToS3(body) {
  console.log(index++);
  return s3.upload({ Bucket: bucketName, Key: filePath, Body: body }).promise();
}
``` 

I checked ParseOne params. The both of the versions of the script below seem to have no impact on the stream count.
```
.pipe(unzipper.ParseOne(}))
or 
.pipe(unzipper.ParseOne({ forceStream: true }))
```

Could you advice what needs to be done to check whether the data is streamed back.

PS: I want to make a tutorial of the same process to simplify it for other developers. I spent 4 days figuring out the issue. Only this plugins seems to be intuitive for streaming the zipped file back to S3

Thank you very much in advance.
Aki

**Comment by ZJONSSON** [comment]
@multiaki I'm not entirely sure what you want to do.   If you want to copy the entire zip file from one s3 bucket to another, you shouldn't need `unzipper`, just put  `s3.getObject().createReadStream()` as the Boddy to the `s3.upload`

If you want to get a single file from a zip file, when you can use `ParseOne` with optional pattern matching to get the first matching file.    This method will only unzip ONE file and returns the stream to the content of the file.

If you want to unzip multiple files from a zip file and upload separately to S3, you have to iterate through the files and call `.stream()` on each entry to get the stream object and use it as a `Body` in the s3upload.  (see my example above, examples in the readme and tests in the test directory)

As to your question on whether the entire file gets loaded or not, whenever you are passing around streams you usually will only have a small part of the file in memory at any given point in time.  Stream buffer only a small amount of memory (highWaterMark) so you could be unzipping a petabyte zip file and never run into memory issues.    If you call `entry.buffer()` only then does all the content get buffered into memory.

**Comment by multiaki** [comment]
@ZJONSSON My main point was toknow whether unzipper.ParseOne unzips entire file and then streams down. or does it unzip and stream at the same time. 
In my code streamToS3(body) is called once. How can I be sure that the code is streaming as soon as it receives the part of a file

**Comment by ZJONSSON** [comment]
@multiaki `ParseOne` returns a stream that is unzipping the underlying file along the way, i.e. `ParseOne` does NOT unzip the entire file before streaming.

The only method that results in an entire file being unzpiped into memory is the `.buffer()` helper method on the `entry` object, which really should only be used if you need to quickly get contents of a file that you know is small.

**Comment by multiaki** [comment]
@ZJONSSON Thank you very much.  Thank you for your time and patience.

**Comment by edcourtney74** [comment]
> ```js
> const zip = s3.getObject({ Bucket: event.bucket, Key: event.key })
>    .createReadStream()
>   .pipe(unzipper.Parse({forceStream: true}));
> 
> for await (const entry of zip) {
>   const Bucket = 'xxxxx';
>   const Key = `/prefix/${entry.path}`;
>   const Body = entry.stream();
>   await s3Client.upload({Bucket, Key, Body}).promise()
> }
> ```
When I try the above, I'm getting a entry.stream is not a function.
Also forceStream is not one of the ParseOptions in the TypeScript type definitions.
Any help you could give would be appreciated.

**Comment by ZJONSSON** [comment]
Hey @edcourtney74 I made a mistake in the example above (I just fixed it).   The `entry`  object itself is a passthrough stream that you can pipe.  

So basically you do:
```js
const Body = entry;
await s3Client.updload({Bucket, Key, Body}).promise()
```

The async iterator option (where you have to use `forceStream`) is recently introduced.  Feel free to do a PR into the Typescript definitions to reflect

**Comment by edcourtney74** [comment]
Thanks, it's working great. Very helpful. I submitted a PR for the Typescript definition.
