### ISSUE TITLE
Streams 50 files to S3, halts/timesout, and continues -- what am I doing wrong?

### ISSUE THREAD

**Issue by wes-r** [ZJONSSON/node-unzipper#184]
I'm trying to stream a zip from S3 and then stream each file to a different bucket in S3. There's other processing that goes on but this is the zip/stream/s3 part.

The issue is I stream 50 files successfully and then the `s3.putObject` of the 51st file times out (no read/write for 200 seconds). Then things continue (my real code has try/catch) and it goes another 50 successfully until the same thing happens again. My PDFs are ~135KB if that helps.

What am doing wrong here?

```js
const files = await unzipper.Open.s3(s3, {
  Bucket: FROM_BUCKET,
  Key: "path/to/file.zip"
}).files;

for (const entry of files) {
  await s3
    .putObject({
      Bucket: TO_BUCKET,
      Key: 'new/path.pdf',
      Body: await file.stream(),
      ContentType: "application/pdf",
      ContentLength: file.uncompressedSize
    })
    .promise();
}
```

Note: I also tried the example at the bottom of this comment: https://github.com/ZJONSSON/node-unzipper/issues/183#issuecomment-596089062 but that failed with a cannot `await`.. and removing the `await` I get a `zip` is not iterable error.

**Comment by wes-r** [comment]
More details, if I change it to `file.buffer()` then instead of getting a hang, the process crashes without errors o_O.

Also note, I tried this in node 8 and now node 12 and same problem.

**Comment by multiaki** [comment]
I see 2 issues.

1. await should be used inside a function. function should start with "async"
2. if you are getting not iterable error, then the files might not be an array. Try to use map, forEach, for loops. One should work. But first, console.log the files object. It might be empty

**Comment by wes-r** [comment]
Ah the code in https://github.com/ZJONSSON/node-unzipper/issues/183#issuecomment-596089062 works with node 12 but not node 8. I think that way of processing the files is working!

Closing!

**Comment by ZJONSSON** [comment]
@wes-r thanks for reporting.  It's worth nothing that by awaiting for each entry in the for-loop you are only unzipping one file at a time..   Since the `Open` methods use random access you can actually do multiple files simultaneously (assuming CPU isn't pegged).   Here is an example using Bluebird map with concurrency of 5:

```js

async function saveFile(file) {
  await s3
    .putObject({
      Bucket: TO_BUCKET,
      Key: 'new/path.pdf',
      Body: await file.stream(),
      ContentType: "application/pdf",
      ContentLength: file.uncompressedSize
    })
    .promise();
}

await Bluebird.map(files, saveFile, {concurrency: 5});
```

**Comment by fyrstelin** [comment]
We have the same issue when using the S3 SDK. It seems that the sockets are not closed by unzipper. Using a signed URL and Open.url solved our problem.

**Comment by oste** [comment]
I am also running into this 50 file limit. I thought I was doing something wrong with rxjs but this seems the more likely cause. See https://stackoverflow.com/questions/65169545/rxjs-zip-not-called-for-every-nested-array/65171739?noredirect=1#comment115219515_65171739

**Comment by jpambrun** [comment]
This should  be reopened. It still stalls at 50 both using `await file.buffer()` or using the `file.stream()`. 

`fileStream.end()` or `fileStream.destroy()` doesn't help either.
