### ISSUE TITLE
on('close') event is fired before stream finishes when archive contains empty directory

### ISSUE THREAD

**Issue by zcaisse9876** [ZJONSSON/node-unzipper#200]
Experiencing an issue where the on('close') event is firing before data is finished being streamed to the filesystem. This issue only occurs when the zip archive contains an empty directory.

Some details:
node.js 8.10
unzipper 0.10.11
MacOS 10.15.4

unzipping archive containing structure
a/sometextfile.txt
a/b/'b is empty'

inside of the on close callback event, i'm immediately checking the file system with the fs synchronous exists api but it always reports that none of the files exist, not even the top level directory. after throwing in a timeout and waiting 1 second, the call to synchronous exists can find all of the files, with the exception of the empty directory (already aware that empty directories are not supported yet)

edit: using the api fs.createReadStream('path/to/archive.zip').pipe(unzipper.Extract({ path: 'output/path' }));

**Comment by ZJONSSON** [comment]
Hopefully this has been resolved by replacing `fstream` with `fs-extra` https://github.com/ZJONSSON/node-unzipper/pull/318/files#diff-ad67f830ededacce71edff0de408c01f6d287c3bb7c95f64cc5c3b0ae7494bdcR30

Empty directories are now explicitly extracted (see [test](https://github.com/ZJONSSON/node-unzipper/blob/master/test/compressed.js#L55-L68))

Published as `unzipper@0.12.1`
