### ISSUE TITLE
Unable to unzip large zip file (2.3GB) using Extract (should use Open instead)

### ISSUE THREAD

**Issue by aeisenberg** [ZJONSSON/node-unzipper#202]
I am having trouble unzipping a large zip file. Here is the code. And when I run this, I get an error "unexpected end of file".

```js
const unzipper = require("unzipper");
const fs = require('fs');

async function unzip(zipfilePath, targetPath) {
  const unzipStream = unzipper.Extract({
    path: targetPath,
  });
  await new Promise((resolve, reject) => {
    const stream = fs.createReadStream(zipfilePath);
    stream.on("error", reject);
    unzipStream.on("error", reject);
    unzipStream.on("close", resolve);
    stream.pipe(unzipStream);
  });
}

unzip(
  "/path/to/zip/file.zip",
  "/path/to/target/directory"
);
```

The zip file I am using is valid according to `unzip -t file.zip`. Also, the file is not easily downloadable though I suspect it will fail for all large zip files of size 2^31 - 1. 

If you want an example of this, I can create a public link for this file.

**Comment by aeisenberg** [comment]
Possibly a duplicate of #29?

**Comment by aeisenberg** [comment]
Couple of more things:

* Using unzipper v0.10.10
* Unzipping on the command line works with no problem
* Zip file size is approximately 2.3G
* File can be downloaded here: https://lgtm.com/api/v1.0/snapshots/1510813321694/cpp

**Comment by aeisenberg** [comment]
Another data-point is implying that there is something about this library. I tried a similar experiment with the node-stream-zip package and was able to unzip the archive file with no problem.

For reference, the code I used here looks like this:

```js
const fs = require('fs');
const StreamZip = require("node-stream-zip");

async function unzip(zipfilePath, targetPath) {
  const zip = new StreamZip({
    file: zipfilePath,
    storeEntries: true,
  });

  zip.on("error", (err) => {
    console.error(err);
    process.exit(-1);
  });

  zip.on("ready", () => {
    fs.mkdirSync(targetPath);
    zip.extract(null, targetPath, (err, count) => {
      console.log(err ? "Extract error" : `Extracted ${count} entries`);
      zip.close();
    });
  });
}
```

**Comment by multiaki** [comment]
> Thanks for the link @multiaki. It's a neat solution, though I'm not sure how relevant this is. We need to extract an entire archive already on disk to another location. I would think that my code above is already doing as much streaming as possible, unless you're seeing something I'm not doing right?

Yeah. Sorry for the confusion. The solutuin was to unzip file from s3 to s3. And the size was 5gb unzipped. I misread the question. I kust wanted to share, because it took me 2 days to come to solution. I thought it would be helpful.

**Comment by ZJONSSON** [comment]
@aeisenberg the issue you are seeing has nothing to do with the size of the file.  It has to do with trusting local file headers which are not guaranteed to be correct.

unzipper provides two ways of accessing a zip file:

#### Open
The preferred way is via `Open` methods using random access.   The `Open` method starts by reading the `CentralDirectory` at the end of the zip file containing correct information about all the entries in the zip file and provides direct access to those entries via streaming.

#### Parse
The legacy method (borrowed from `unzip`) is streaming the entire file from start to finish and use the local file headers along the way to get the metadata and understand the compressed size of each file.  In some cases filesize is unknown in the local header and we must rely on end-of-file marker to understand when the current file ends and the next local file header begins.

While the Parse method usually works, it's never guaranteed to work as relies on the local headers not the Central Directory at the end (source of truth).    See https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api for more detail

In the sample zip file you shared you will notice that the individual local file headers do not share information about the size of each underlying file.   The parse method fails on this underlying file:

```
{
  fileSizeKnown: false,
  vars: {
    versionsNeededToExtract: 20,
    flags: 2056,
    compressionMethod: 8,
    lastModifiedTime: 30522,
    lastModifiedDate: 20678,
    crc32: 0,
    compressedSize: 0,
    uncompressedSize: 0,
    fileNameLength: 67,
    extraFieldLength: 0,
    lastModifiedDateTime: 2020-06-06T14:57:52.000Z
  },
  props: {
    path: 'frederik-h_gcc-lgtm_2daf3b0/db-cpp/default/cache/pages/1f/c2.pack.d',
    pathBuffer: <Buffer 66 72 65 64 65 72 69 6b 2d 68 5f 67 63 63 2d 6c 67 74 6d 5f 32 64 61 66 33 62 30 2f 64 62 2d 63 70 70 2f 64 65 66 61 75 6c 74 2f 63 61 63 68 65 2f 70 ... 17 more bytes>,
    flags: { isUnicode: 0 }
  }
}
```

with `unexpected end of file` - meaning that the Parser was expecting an end-of-file marker but never found it.

If we look at the same file in the central directory we see the exact size and can easily extract it:

```
{
  signature: 33639248,
  versionMadeBy: 20,
  versionsNeededToExtract: 20,
  flags: 2056,
  compressionMethod: 8,
  lastModifiedTime: 30522,
  lastModifiedDate: 20678,
  crc32: 17633741,
  compressedSize: 146733,
  uncompressedSize: 284014,
  fileNameLength: 67,
  extraFieldLength: 0,
  fileCommentLength: 0,
  diskNumber: 0,
  internalFileAttributes: 0,
  externalFileAttributes: 0,
  offsetToLocalFileHeader: 1983172628,
  lastModifiedDateTime: 2020-06-06T14:57:52.000Z,
  pathBuffer: <Buffer 66 72 65 64 65 72 69 6b 2d 68 5f 67 63 63 2d 6c 67 74 6d 5
f 32 64 61 66 33 62 30 2f 64 62 2d 63 70 70 2f 64 65 66 61 75 6c 74 2f 63 61 63 
68 65 2f 70 ... 17 more bytes>,
  path: 'frederik-h_gcc-lgtm_2daf3b0/db-cpp/default/cache/pages/1f/c2.pack.d',
  isUnicode: 0,
  extra: {},
  comment: '',
  type: 'File',
  stream: [Function (anonymous)],
  buffer: [Function (anonymous)]
}
```

My recommendation: Always use the Open methods except in the cases where you absolutely can not.

Here is how you can extract with `Open` - you can also roll your own by calling `stream()` method on the entries you want to extract and pipe it to the target writable stream

```
async function unzip(zipfilePath,  targetPath) {
  const directory = await unzipper.Open.file(zipfilePath);
  await directory.extract({path: targetPath});
}
```

**Comment by aeisenberg** [comment]
Thanks for your detailed answer. I'll try this out and hopefully it will fix the issue.

**Comment by aeisenberg** [comment]
Your suggestion works. I updated the issue description and closing this now. Thanks again.
