### ISSUE TITLE
on entry never runs

### ISSUE THREAD

**Issue by george-norris-salesforce** [ZJONSSON/node-unzipper#206]
```
return new Promise((resolve, reject) => {
      createReadStream(pathToZip)
        .pipe(unzipper.Extract({ path: pathToUnzip }))
        .on('entry', (entry) => {
            ....
```

I've set a debugger on `entry` and it never gets there. It goes straight to `finish` event.

**Comment by ZJONSSON** [comment]
The `Extract` method does not emit `entry`, it simply extract all files to disk.   If you remove the `pipe(unzipper.Extract...` you should get entry events and handle them directly.

**Comment by george-norris-salesforce** [comment]
After unzipper extracts, `unzipper.Extract({ path: pathToUnzip })` how do you pipe the entires from the unzipped file?
