### ISSUE TITLE
stream.pipeline [ERR_STREAM_PREMATURE_CLOSE]: Premature close

### ISSUE THREAD

**Issue by boggddan** [ZJONSSON/node-unzipper#228]
Hello. Could help me. I am using I am using [stream.pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) but I have an error **[ERR_STREAM_PREMATURE_CLOSE]: Premature close**. The file is unpacked, apparently the error occurs due to the fact that it happens with method destroy() instead of end().

[stackoverflow](https://stackoverflow.com/a/61379055)

How do I fix this error? Thank you.

Ububtu 20.10 x64
Node.js 15.4.0

```js
import fs from 'fs';
import { Transform } from 'stream';
import { pipeline } from 'stream/promises';
import path from 'path';
import unzipper from 'unzipper';

const fileNameZip = '17-ufop.zip';

(async () => {
  await pipeline(
    fs.createReadStream(fileNameZip),
    unzipper.Parse({ forceStream: true }),
    async (source) => {
      for await (const chunk of source) {
        const fileName = path.basename(chunk.path);
        console.log(fileName)
        if (/17\.1-EX_XML_EDR_UO/.test(fileName)) {
          await pipeline(chunk, fs.createWriteStream(fileName));
        } else {
          chunk.autodrain();
        }
      }
    }
  );

  console.log('Done');
})();
```

Error

```bash
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:278:15)
    at Parse.onclose (node:internal/streams/end-of-stream:117:38)
    at Parse.emit (node:events:388:22)
    at Parse.<anonymous> (/home/user/Project/ufopParser/node_modules/unzipper/lib/parse.js:29:10)
    at Parse.emit (node:events:388:22)
    at finish (node:internal/streams/writable:734:10)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

**Comment by eberlitz** [comment]
Any solutions to this? I'm facing the same error here:

```ts
await pipeline(
      createReadStream('./sample.zip'),
      Parse({ forceStream: true }),
      async function processZip(entries: AsyncIterable<Entry>) {
        for await (const entry of entries) {
          const { path, type } = entry;
          console.log(path, type);
          await entry.autodrain();
        }
        return true;
      }
    );
```

Gives me `Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close`.

Node version v14.17.0
unzipper@0.10.11

**Comment by zachsa** [comment]
I have also recently started to get this

**Comment by theguriev** [comment]
Same error on our side after update :(

**Comment by tinesoft** [comment]
any updates on this ?

**Comment by tinesoft** [comment]
This error looks like a misuse of the stream API in the first place, that is now more severely reported by Node since v17+.

Maybe @mcollina and @ronag (nodejs core members) can give an hand here?

I'd gladly provide my assistance with a repro project, but unfortunately I don't know enough about streams to provide a full PR... :-(

**Comment by wolfymaster** [comment]
I am also now facing this issue. This was not an issue on Node v12.. but we recently upgraded to Node v18 and I'm receiving this error. I'm not able to find a workaround.

**Comment by BrunoCambianica** [comment]
👋 
I had the same issue as well when using the async for of.
I did switch to Transform from stream and it works correctly:
```
stream.pipe(
    new Transform({
      objectMode: true,
      transform(entry, _, callback) {
        const fileName = entry.path

        if (entry.type === 'File') {
          // process data
          callback()
        } else {
          entry.autodrain();
          callback()
        }
      },
    })
)
```

**Comment by ronag** [comment]
Is this a problem in Node 19 as well?

**Comment by eamon0989** [comment]
I'm also facing this issue on Node 18, as mentioned above, it seems to be an issue with `async for...of`. @wolfymaster's [solution](https://github.com/ZJONSSON/node-unzipper/issues/228#issuecomment-1294451911) above worked as a (hopefully temporary) fix.

**Comment by some-dev-1** [comment]
Can confirm that @wolfymaster's [solution]( https://github.com/ZJONSSON/node-unzipper/issues/228#issuecomment-1294451911) works for me too.

**Comment by bassmanitram** [comment]
Unfortunately I use an async/await-based batching algorithm right in the middle of that `do some stuff, so the function has to be async, which of course is the root of the issue. I don't have the time or budget to completely refactor the code to make that work. https://github.com/ZJONSSON/node-unzipper/issues/269 provides the real fix, and my comment there explains what I'm doing to get the fix, pending the PR merge.

**Comment by ZJONSSON** [comment]
Will merge later today

**Comment by ZJONSSON** [comment]
This PR has been published as a patch version https://github.com/ZJONSSON/node-unzipper/pull/274

**Comment by bassmanitram** [comment]
THANK you - and I apologize for my doubts!
