### ISSUE TITLE
issue with skipped files when using stream + async iterators

### ISSUE THREAD

**Issue by Privatecoder** [ZJONSSON/node-unzipper#234]
I have an issue with the following xlsx file which I am trying to extract and parse using async iterators

- v12.18.0/macOS

[test.xlsx](https://github.com/exceljs/exceljs/files/6054105/test.xlsx)

there seems to be an issue with unzipper using async iterators. any await (sample: 1000ms) results in more or less of the succeeding contents of the zip (here xlsx) to not be processed:

```
const fs = require('fs');
const unzipper = require('unzipper');

const test = async () => {
    const stream = fs.createReadStream('test.xlsx');
    const zip = stream.pipe(unzipper.Parse({forceStream: true}));

    for await (const entry of zip) {
        console.log(entry.path);
        await new Promise(resolve => setTimeout(resolve, 1000));
    }
}

test();
```

output:

```
docProps/core.xml
```

vs.

```
const fs = require('fs');
const unzipper = require('unzipper');


const test = () => {
    const stream = fs.createReadStream('test.xlsx');
    const zip = stream.pipe(unzipper.Parse());

    zip.on('entry', entry => {
        console.log(entry.path);
    })
}

test();
```

output:

```
docProps/core.xml
docProps/app.xml
xl/worksheets/sheet1.xml
xl/workbook.xml
xl/theme/theme1.xml
xl/styles.xml
[Content_Types].xml
_rels/.rels
xl/_rels/workbook.xml.rels
```

I also posted this issue here: https://github.com/exceljs/exceljs/issues/962

**Comment by Privatecoder** [comment]
upgrading node to v14.16.0 fixes the issue.

**Comment by zhukovsv** [comment]
Hi Everyone,

I reproduced this issue: **Failed: Cannot read property 'sheets' of undefined**

Configuration settings:
1. node - v: 14.16.0

2. "exceljs": "^4.2.1"

3. test File: [testFile.xlsx](https://github.com/exceljs/exceljs/files/6171846/testFile.xlsx)

4.  Code:
```
const ExcelJS = require('exceljs');
const pageComparisonXLSXFilePath = './testFile.xlsx';
const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(pageComparisonXLSXFilePath); 
const worksheet = workbook.getWorksheet(1);
const rowC = worksheet.rowCount;
for (const row of worksheet.getRows(1, rowC)) {
  console.log(row.values);
}
``` 

5. Steps to reproduce:
         1. Download file -> exec code -> exception: Failed: Cannot read property 'sheets' of undefined. 
         but
         2. If I open this file by MSExcel and then simply save this file and close it -> code executes correctly.

Could you help me?

Regards, Sergei.

I also posted the same description here: exceljs/exceljs#962
