### ISSUE TITLE
bug: `unzipper.Extract()` resolves promise before complete extraction of zip

### ISSUE THREAD

**Issue by roerohan** [ZJONSSON/node-unzipper#240]
In the following example, the promise from `unzipper.Extract()` is resolved before the unzipping task is actually over.

```ts
import util from 'util';
import stream from 'stream';
import path from 'path';
import AWS from 'aws-sdk';
import glob from 'glob';

s3 = new AWS.S3({
    accessKeyId,
    secretAccessKey,
    region,
});

async function extract() {
    const pipelinePromise = util.promisify(stream.pipeline);

    // params has AWS SDK S3 getObject params
    // unzipPath is the path to which the zip will be extracted
    await pipelinePromise(
        s3.getObject(params).createReadStream(),
        unzipper.Extract({ path: unzipPath }),
    );
}

async function main() {
    await extract();
    const globPromise = util.promisify(glob);

    // unzipPath is same as before
    const files = await globPromise(path.join(unzipPath, '**', '*'), { nodir: true });
    console.log(files);
}

main();
```

When you check the console after running `main()`, a list of files that are extracted in the directory is logged. This list changes every time you execute this code-snippet and often has some files missing (that are actually present in the original zip).

Of course, when you later list the files in the directory (using `ls` or something), all the files are extracted properly and present. However, the promise is resolved prematurely, and the glob pattern does not always show all the files.

> Note: When you run the `unzip` binary using `child_process` and await that, then the glob pattern does return all the files correctly.

**Comment by BenShelton** [comment]
I had the same issue, turns out it's because using a pipeline with promisify is listening for the wrong event, `unzipper` emits a `close` event when everything has been written to disk.

Instead I had to make my own promise:
```js
function extract(zipStream, outputPath) {
  return new Promise((resolve) => {
    zipStream
      .pipe(unzipper.Extract({ path: outputPath }))
      .on('close', () => {
        resolve()
      })
  })
}
```

**Comment by Wambosa** [comment]
Thank you @BenShelton 
I was encountering this same issue and didn't realize it. Wrapping in a promise works as expected.

**Comment by Chuckytuh** [comment]
Stating what might be obvious to many but, based on @BenShelton's answer, ensure that you properly handle errors from the zipStream stream given that `.pipe` doesn't "flow" errors into piped functions nor automatically closes streams "down the pipe"

**Comment by ZJONSSON** [comment]
`extract` has a `promise` method.   So the following should work:

```
const extractor = unzipper.Extract({ path: unzipPath });
await pipelinePromise(
        s3.getObject(params).createReadStream(),
        extractor
);
await extractor.promise();
```
