### ISSUE TITLE
Windows: Extract fails if zip contains file with newline in filename

### ISSUE THREAD

**Issue by llimos** [ZJONSSON/node-unzipper#249]
I managed to get a zip file where one of the files inside it has a newline in the filename.

When using Extract on a Windows machine, I get the following error:

```
[Error: ENOENT: no such file or directory, open 'C:\local\Temp\extracted\File
With
Spaces.txt']

{
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\local\\Temp\\extracted\\File\n' +
    'With\n' +
    'Spaces.txt'
}
```

I think the error is happening on the write, because the file isn't there.

I know this isn't a common case, but the zip is valid, so perhaps it could be handled simply by stripping out the newlines from the filenames when extracting?

**Comment by ZJONSSON** [comment]
Using the `Open` methods, you can iterate through the files, transform the original filename (such as removing the newline), and save it safely.   The extract method however doesn't provide this functionality out of the box
