### ISSUE TITLE
Extract Password Protected Zip File to Directory

### ISSUE THREAD

**Issue by DMcKay-Stack** [ZJONSSON/node-unzipper#258]
Where in this code would you put the password to extract the password protected zip file to a directory?  I am working with a downloaded .bak that is password protected.  I need to keep it in the same format because once I extract it, I'm immediately loading it to an mssql rds.  Manually, I use 7-zip which provides an option to enter a password.  In NodeJS this is not an option.

fs.createReadStream('path/to/archive.zip').pipe(unzipper.Extract({ path: 'output/path' }));

**Comment by ZJONSSON** [comment]
unzipping password protected files is supported using the `Open` methods (see readme)
Please note that unzipper does not work with 7zip format
