### ISSUE TITLE
release version 0.10.13 to npm

### ISSUE THREAD

**Issue by code-is-art** [ZJONSSON/node-unzipper#262]
Please release this version as the custom Open is not in the current npm version 0.10.11.

**Comment by Hiroshiba** [comment]
I am one of those waiting for the next npm package...!

ref.

- https://github.com/ZJONSSON/node-unzipper/issues/256

**Comment by emmercm** [comment]
I believe v0.10.14 was released a week ago.

**Comment by Hiroshiba** [comment]
Thanks a lot!!!

**Comment by lucasrmendonca** [comment]
@code-is-art @ZJONSSON can we close this issue as per @emmercm's comment above?
