### ISSUE TITLE
How can I make it faster?

### ISSUE THREAD

**Issue by tejasnayak25** [ZJONSSON/node-unzipper#264]
I'm using the node-unzipper framework to unzip some password-protected zip files and it's taking so...so long. I want to make it faster. Is there any way in which I can improve its speed?

**Comment by dkostenevich** [comment]
@tj-likes-coding please take a look to #38

**Comment by ZJONSSON** [comment]
closed with https://github.com/ZJONSSON/node-unzipper/pull/316  (Thanks @lechuhuuha )
published as `unzipper@0.12.1`
