### ISSUE TITLE
In Node v18 or higher: unzipper.Parse({forceStream: true}) throws Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close | SOLVED

### ISSUE THREAD

**Issue by Mikael-Kolehmainen** [ZJONSSON/node-unzipper#269]
As the title says, unzipper will throw `Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close` but still execute successfully. This happens in Node v18 and higher while using the asyinc iterators.
For [example](https://www.npmjs.com/package/unzipper)  (from the npm page) will throw the error:
`const zip = fs.createReadStream('path/to/archive.zip').pipe(unzipper.Parse({forceStream: true}));
for await (const entry of zip) {
  const fileName = entry.path;
  const type = entry.type; // 'Directory' or 'File'
  const size = entry.vars.uncompressedSize; // There is also compressedSize;
  if (fileName === "this IS the file I'm looking for") {
    entry.pipe(fs.createWriteStream('output/path'));
  } else {
    entry.autodrain();
  }
}`

I did find a solution for this but couldn't push my branch and make a pull request, it's a one liner so I'll write it here.
In the file lib/parse.js on line 29 before `self.emit('close')`, I wrote `self.emit('end')`, which got the code working without the error being thrown.

It would be nice if you could update the repo and the npm package with this change, if this solution doesn't bring any other problems that I'm not aware of.

Please let me know if there's any questions.

**Comment by mr-smit** [comment]
or you can temporarry ignore error until update using try catch block

try {
 // extract here
}catch(err){}

**Comment by bassmanitram** [comment]
This one is kind of a deal-breaker for promise-based workflows - the fixes by @Mikael-Kolehmainen and @Durisvk certainly work... but since the last PR merge was more than a year ago, I'm getting a _bit_ concerned that perhaps this 2 Million+ downloads-a-week module is not now receiving the support it warrants?

In the mean time, I hack in the fixed `parse.js` after `npm install`.

**Comment by ZJONSSON** [comment]
resolved with https://github.com/ZJONSSON/node-unzipper/pull/274/files
