### ISSUE TITLE
Possible copyright violation

### ISSUE THREAD

**Issue by ngg** [ZJONSSON/node-unzipper#272]
This package depends on the [binary](https://www.npmjs.com/package/binary) package which itself depends on the [buffers](https://www.npmjs.com/package/buffers) package.
The buffers package has no license, meaning that nobody is given any right to use or redistribute that library.

As both the binary and buffers packages are unmaintained (their last release was 11 years ago and Github links are broken), I'm reporting this issue here. Do you have any kind of written agreement from the author of the buffers package?

**Comment by ZJONSSON** [comment]
The binary package is published by the same author as the buffers package and issued under an open-source license.   
In this repo we only reference the open source package
