### ISSUE TITLE
Files are messed up

### ISSUE THREAD

**Issue by dweber019** [ZJONSSON/node-unzipper#28]
I'm downloading a zip file with "request" and try to extract it with this library.

Sadly some files are messed up after extraction.

This is the zip file I'm downloading and extracting: https://tools.hana.ondemand.com/additional/sap-webide-personal-edition-1.45.3-prod-macosx.cocoa.x86_64.zip

E.g. for a file messed up eclipse/orion 

Here the code I use this plugin (it's not stable or clean as I'm currently build up): https://github.com/dweber019/ui5-web-ide-installer/tree/develop

Any help very appreciated.

**Comment by ZJONSSON** [comment]
Unfortunately when I open the link I get an error when I try the link and therefore its hard to debug:
![image](https://cloud.githubusercontent.com/assets/1082488/22864320/466a9d7e-f11d-11e6-8e43-9281e58b5725.png)

Does this file exists in a different location?  Which method are you using to unzip, i.e. open.url or are you doing request yourself and piping into unzipper?

**Comment by dweber019** [comment]
Ahh sorry go to this site and accept the eula https://tools.hana.ondemand.com/#sapui5.

**Comment by dweber019** [comment]
To your questions:
- Yes this is the location
- I'm using my own request to download as the zip file is over 500MB big and I like to show the process

Here my code for extracting:
```
fs.createReadStream('webide.zip')
    .on('end', () => {
      log(chalk.green.bold('Web IDE installed to'), installationPath);
      cb();
    })
    .pipe(unzipper.Extract({ path: installationPath }));
```

**Comment by ZJONSSON** [comment]
Few comments / questions
*  When you say files are messed up, what do you mean exactly?  Are all the files there but binaries are corrupted, or are you missing files?   Are text files corrupted?
* `.on('end'..` in the snippet above will wire before the files are unzipped.  You would have to put `.on('finish',cb)` behind the `.pipe(unzipper` to be guaranteed to `cb` only when actually done
* Is is possible that the file hasn't complete downloading before you are unzipping?  (you can really only start unzipping after `.on('finish')` of the writeStream
* With unzipper you should not have to write a temporary file, you should be able to `request` directly into `unzipper`
* If any files are corrupted you could check if that is also the case using the `open.url` interface https://github.com/ZJONSSON/node-unzipper#openurlrequestlibrary-url

Here is a simple example seems to  extracts all the files - not sure if they are corrupted:
```js
const request = require('request');
const unzipper = require('unzipper');

const url = 'https://tools.hana.ondemand.com/additional/sap-webide-personal-edition-1.45.3-prod-macosx.cocoa.x86_64.zip';
request({ url: url, headers: { Cookie: 'eula_3.1_agreed=tools.hana.ondemand.com/developer-license-3.1.txt' } })
  .pipe(unzipper.Extract({path:'./sap-webide'}))
  .on('finish',() => console.log('done'))
  .on('error', e => console.log('error',e));
```

And here is an extension where we notify progress every second:

```js
const request = require('request');
const unzipper = require('./unzip');
const Stream = require('stream');

// log progress every second
let total,progress=0;
let counter = setInterval( () => console.log(progress/total)*100,1000);

const url = 'https://tools.hana.ondemand.com/additional/sap-webide-personal-edition-1.45.3-prod-macosx.cocoa.x86_64.zip';

request({ url: url, headers: { Cookie: 'eula_3.1_agreed=tools.hana.ondemand.com/developer-license-3.1.txt' } })
  // Note down the content length of the reponse to track progress
  .on('response',d => total = d.headers['content-length'])
  // Use a Transform as PassThrough + counting the length of data
  .pipe(Stream.Transform({
    transform: (d,e,cb) => { progress += d.length; cb(null,d);  }
  }))
  .pipe(unzipper.Extract({path:'./sap-webide'}))
  .on('error', e => console.log('error',e))
  .on('finish',() => {
    clearInterval(counter);
    console.log('done');
  });
```

**Comment by dweber019** [comment]
I'll just started testing with your snippets.

To your questions:
- Yes some files are corrupted
- Thanks for the clarification with "finish"
- Im using the exact example here https://www.npmjs.com/package/request-progress inclusive the library it self
- Will try thanks

**Comment by dweber019** [comment]
I tested with your `simple example` above but doesn't seam to work as the file `eclipse/orion` is still corrupted.

I also tried to do it with open.url but no success as no promise handler will fire (not then and not catch):
```javascript
unzipper.Open.url(request, { url: 'https://tools.hana.ondemand.com/additional/sap-webide-personal-edition-1.45.3-prod-macosx.cocoa.x86_64.zip', headers: { Cookie: 'eula_3.1_agreed=tools.hana.ondemand.com/developer-license-3.1.txt' } })
    .then(function (d) {
      var file = d.files.filter(function (d) {
        return d.path === 'artifacts.xml';
      })[0];
      return file.buffer();
    })
    .then(function (d) {
      console.log(d.toString());
      cb();
    })
    .catch((err) => console.log(err));
```

**Comment by dweber019** [comment]
I also just downloaded the zip file with `request-progress` and `request` library and extracted manually with `The Unarchiver` (macOS Programm) and it worked. So no corrupted files.

**Comment by mhr3** [comment]
I also just encountered this problem, unzipper doesn't uncompress the complete file, I have this piece of code:
```
var s = fs.createReadStream('./build.zip');
s.pipe(unzip.Parse()).on("entry", (entry) => {
  if (entry.path.endsWith('.log')) {
    entry.pipe(fs.createWriteStream('./unzipped.log'));
    entry.on('data', (chunk) => { console.log("chunk:", chunk && chunk.length); });
    entry.on('finish', () => { console.log("Done!"); });
    return;
  }
  entry.autodrain();
});
```
After running this, `unzipped.log` is only 67438 bytes, but if I unzip it with the regular `unzip` utility, the file is 170447 bytes.

**Comment by ZJONSSON** [comment]
@mhr3 can you try removing the `.on('data')`?  `unzipper` is designed to manage backpressure and both `.piping` and using `.on('data'` might cause conflics.   If that is of no help  can you share a zip file that does not work for you?

@dweber019 I still need to investigate further.  Have you figured something else out on your end?

**Comment by dweber019** [comment]
@ZJONSSON Sadly no success.

**Comment by ZJONSSON** [comment]
New RC - `unzipper@0.9.0-rc5`   https://github.com/ZJONSSON/node-unzipper/issues/29
See also: https://github.com/ZJONSSON/node-unzipper/issues/29
Not sure if this contains fixes - this issue is still open

**Comment by mhr3** [comment]
@dweber019 I solved this issue by using [unzip-stream](https://www.npmjs.com/package/unzip-stream)

**Comment by nucc1** [comment]
It might be important to pay attention to what code you have *after* you think you have unzipped. 

You might have a line of code that causes the interpreter to kill/clean up the unzip before it has finished extracting. 

See for example: https://stackoverflow.com/a/44282243/576514

**Comment by ZJONSSON** [comment]
The original file in question is no longer available.  It is quite possible that this error has been fixed thanks to (i) waiting for `finish` before cleaning up as per @nucc1 suggestion and (ii) the zip64 headers are now properly parsed in the latest version (fixed by @dimfeld)

Please reopen (or open new issue) if you still see this with a link to the zip file in question and a copy of the code used to extract.
