### ISSUE TITLE
`Open.file()` returns unicode replacement character(�) for unicode filenames

### ISSUE THREAD

**Issue by emmercm** [ZJONSSON/node-unzipper#280]
Given a unicode archive entry name such as:

`Brasileirão de Seleções 2020.sfc`

Calling `(await unzipper.Open.file()).files` will return `�` instead of unicode characters:

`Brasileirao de Sele�oes 2020.sfc`

This is on macOS 13.3.1.

---

This could be related to https://github.com/ZJONSSON/node-unzipper/issues/35, it doesn't look like that was addressed in any PR. The suggested fix in that issue doesn't work here, the file's `pathBuffer.toString('utf-8') === path` so the buffer is wrong. The file has `isUnicode === 0`.

**Comment by ZJONSSON** [comment]
[test.zip](https://github.com/ZJONSSON/node-unzipper/files/15053408/test.zip)

```
 .on('entry', function (entry) {
    const fileName = entry.path;
    const type = entry.type; // 'Directory' or 'File'
    const size = entry.vars.uncompressedSize; // There is also compressedSize;
    console.log('using unzipper');
    console.log(fileName);
  });
 ```
 shows the characters:

![image](https://github.com/ZJONSSON/node-unzipper/assets/1082488/c06c0d6b-625d-4757-a839-ebcec78c7787)

If this is still an issue can you share a zip file that doesn't work, and confirm which unzipper version you are using
