### ISSUE TITLE
Zlib Error Unzipping Large Files

### ISSUE THREAD

**Issue by sd-charris** [ZJONSSON/node-unzipper#29]
I am having trouble unzipping a large zip file.. It contains 1 text file, uncompressed it is about 35 GB and compressed it is about 2.38 GB.  I am attempting to The error I get is:

Error: too many length or distance symbols
    at Zlib._handle.onerror (zlib.js:370:17)

I can replicate the issue with the Open.url example, replacing your 500MB file with my large one.  As well the issue is replicated with the "ParseOne" function.  Any idea as to what might be going on?

**Comment by ZJONSSON** [comment]
Can you share a link to the file?   Can you unzip with regular tools?

If not can you try  `npm install unzipper@0.9.0-rc5`
https://github.com/ZJONSSON/node-unzipper/pull/30

This version provides option to ask fetch the `raw` gzip - which you can inflate manually to check which tool fail the actual gzip.   You can get raw either through entry.raw (when using `Open.url`) or `unzipper.Parse({raw:true})`

**Comment by sd-charris** [comment]
I will see if I can upload a file of similar size to a public bucket.  

My initial findings lead me to believe it is a result of zipping the file from the windows 10 built in tool which uses Zip v4.5.  When I use 7zip I and select "deflate" or the legacy v2.0 it appears the large file works.  Mind you a small file in Zip v4.5 works also.  I will give the rc candidate you posted a shot and see if I can gather more info...

**Comment by ZJONSSON** [comment]
Thanks much appreciated!!

**Comment by ZJONSSON** [comment]
For reference: here is a similar issue reported https://github.com/EvanOxfeld/node-unzip/issues/48 that seems to work fine with unzipper - modified example below:

```js
var request = require('request');
var unzip = require('unzipper');

var parser = unzip.Parse();

parser.on('error', function (error) {
    throw error;
});
parser.on('entry', function (entry) {
    console.log(entry.type, entry.path);
    entry.autodrain();
});

parser.on('close', function () {
    console.log('done');
});

request('http://geolite.maxmind.com/download/geoip/database/GeoLite2-City-CSV.zip').pipe(parser);
```

**Comment by ZJONSSON** [comment]
@sd-charris any luck in finding a public bucket that fails?

**Comment by ZJONSSON** [comment]
Closing.  Please reopen if you are able to share a file that replicates the issue

**Comment by RezaRahmati** [comment]
I am getting same error on a large zip file, 32GB file , 
Unfortunately file contains sensitive data not able to share it

**Comment by RezaRahmati** [comment]
I found the fix, in case someone else having same issue 

I missed `entry.autodrain();` in the `on('entry'` method

my final code

```
            const parser = unZipper.Parse({ raw: true, verbose: true });
            await file
                .createReadStream()
                .pipe(parser)
                .on('entry', entry => {
                    const filePath = this.getExtractPath(file.name);
                    const destination = this.fileStorageService.getFile(bucketName, `${filePath}/${entry.path}`);
                    entry.pipe(destination.createWriteStream()).on('error', err => {
                        throw err
                    });

                    entry.autodrain(); // this line was missing
                })
                .on('error', error => {
                    console.error(error);
                    throw error
                })
                .promise();
```

**Comment by JannetGen** [comment]
If you’re still seeing this, I’d check whether the ZIP is being streamed completely before passing it to unzipper. Also worth testing with a known-good archive to rule out corruption. That can help narrow down whether the issue is with the input file or the extraction process.
