### ISSUE TITLE
buffers has no license

### ISSUE THREAD

**Issue by antoniobeltran** [ZJONSSON/node-unzipper#293]
Not sure if this is the place to ask, but I'm using node-unzipper, and this uses [buffers](https://www.npmjs.com/package/buffers) which is used by binary of which node-unzipper references. Security alarms went off stating that there is no license and the github accounts have been deleted. I'm wondering what your thoughts are on this.

**Comment by k0s15** [comment]
Hi All,
I also have the same concerns on this.

**Comment by dubzzz** [comment]
Exactly the same concern on my end

**Comment by petuomin** [comment]
It seems like the author of `binary` and `buffers` packages meant to open source both packages. However since `buffers` is not explicitly marked as open source, linking to it requires permission which seems impossible to obtain. This is the case even when it is a transitive dependency.

**Comment by ZJONSSON** [comment]
https://github.com/ZJONSSON/node-unzipper/pull/283 merged, thanks all
