### ISSUE TITLE
Uncaught Error when using parseOne

### ISSUE THREAD

**Issue by ecofi** [ZJONSSON/node-unzipper#328]
Hi,

I'm getting "Uncaught Error: PATTERN_NOT_FOUND" for one zip file (for other zip files the code is working). It is pointing to this source as part of the unzipper.parseOne function. 

inStream.pipe(Parse(opts))
    .on('error',function(err) {
      outStream.emit('error',err);
    })
    .pipe(transform)
    .on('error',Object)  // Silence error as its already addressed in transform
    .on('finish',function() {
      if (!found)
        outStream.emit('error',new Error('PATTERN_NOT_FOUND'));
      else
        outStream.end();
    });

How can I catch this error in my code when using unzipper.parseOne(entryPath) ?

**Comment by ZJONSSON** [comment]
I would strongly recommend using the `Open` methods that use the central directory (which is the source of truth) rather than the local file headers used by `ParseOne` - check the readme and the tests for examples.

Alternatively you can securely share the zip file with me and I can take a look
