### ISSUE TITLE
UTF8 support?

### ISSUE THREAD

**Issue by ColonelBundy** [ZJONSSON/node-unzipper#35]
Hint: Title.

**Comment by ZJONSSON** [comment]
Thanks for the suggestion @ColonelBundy - optional `encoding` in options that coerces the buffers?    What would be the ideal interface?   

If you are in a rush you can also just throw this one-liner in the stream pipeline below the unzipper:
```js
.pipe(Stream.Transform({transform: (d,e,cb) => cb(d.toString('utf-8')) }))
 // utf-8 comes out here
```

**Comment by ColonelBundy** [comment]
Thank you! And really good work on this!

**Comment by hellorayza** [comment]
Excuse,I have a problem.When zip contain a folder name encoding utf-8,unzip all file name(encoding utf-8) was wrong,Otherwise correct。
