### ISSUE TITLE
entry.size undefined?

### ISSUE THREAD

**Issue by ColonelBundy** [ZJONSSON/node-unzipper#36]
Even though the example shows use of ```entry.size``` this does not exist on the entry object at all.

**Comment by ZJONSSON** [comment]
Good catch - yes the `size` does not exist on the `entry` when the `entry` is emitted (it's defined later see here https://github.com/ZJONSSON/node-unzipper/blob/master/lib/parse.js#L110-L144) - This looks to be an inherited behaviour from https://github.com/EvanOxfeld/node-unzip

I do have a PR that tries to simplify the API across top->bottom streaming, vs random access here:  https://github.com/ZJONSSON/node-unzipper/pull/30   This branch flips the sequence, ensuring variables have been placed on the `entry` before it's emitted (see here https://github.com/ZJONSSON/node-unzipper/blob/e19a4d8f0d9545eb58eb4b3858dfe10bb2983436/lib/parse.js#L65-L83)
