### ISSUE TITLE
any ETA on _transform implementation?

### ISSUE THREAD

**Issue by ColonelBundy** [ZJONSSON/node-unzipper#37]
Even though we have an example using it, it's not implemented.
Any ETA on this? If not I _might_ be able to squeeze in a pr.

**Comment by ZJONSSON** [comment]
The Transform stream is part of node core.  The example you mention had a typo which I just [fixed](https://github.com/ZJONSSON/node-unzipper/commit/e90f5f57b2b3eee25f5f6ea729e0ff9447af5d3b):  there should not be an underscore prefix when defining the `transform` method inside `new Transform(`

See: https://nodejs.org/api/stream.html#stream_new_stream_transform_options

Please reopen if you still have issues.

**Comment by ColonelBundy** [comment]
Right my bad, I tried using your example and the _transform threw me off

**Comment by ZJONSSON** [comment]
Thanks for spotting it!

**Comment by ColonelBundy** [comment]
Also I'd like to ask, feels dumb to open an issue about this. How can we deal with zip bombs? maybe not the traditional one but something similar such as a million nested directories etc...? 
Can we implement some kind of protection against overflows? Or get a count of files etc?

**Comment by ZJONSSON** [comment]
The plain vanilla `Parse()` goes through the file sequentially, so I don't see exactly how a zip bomb could blow up the extract.  But ideally we would include a zip-bomb test files and add tests.
