### ISSUE TITLE
Auth for Open.url

### ISSUE THREAD

**Issue by sabrehagen** [ZJONSSON/node-unzipper#42]
The docs don't explain how to add custom options to request when using `unzipper.Open.url(request,'my-url')`. To save others digging through the code (like myself) it would be useful to specify that the second parameter can take an options object which is passed to request, not just a url.

**Comment by ZJONSSON** [comment]
Great suggestion, do you mind doing a PR with a language that makes sense?

**Comment by ZJONSSON** [comment]
Thanks again!
