### ISSUE TITLE
Can this unzip a KMZ?

### ISSUE THREAD

**Issue by junerockwell** [ZJONSSON/node-unzipper#44]
The KMZ has a `doc.kml` file inside it. But it can only be accessible programmatically once the KMZ has been unzipped.

I've tried changing the KMZ file's extension from `.kmz` to `.zip` and then unzip the file from there. However, the KMZ file's `.name` properly is read-only.

**Comment by ZJONSSON** [comment]
The extension should be irrelevant here.  If you want me to take a look, please reopen with a link to the file and the code that you are executing
