### ISSUE TITLE
DefinitelyTyped implementation

### ISSUE THREAD

**Issue by nagapavan** [ZJONSSON/node-unzipper#46]
unzipper seems to be not there on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
Any possibility of providing the `types` support?

**Comment by ZJONSSON** [comment]
This seems to be done ([see here](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?utf8=%E2%9C%93&q=is%3Apr+unzipper))
