### ISSUE TITLE
7z support

### ISSUE THREAD

**Issue by cervenyprofiq** [ZJONSSON/node-unzipper#51]
unzipper is not able unzip `7z` file. It shows this error:
```
Unhandled rejection Error: invalid signature: 0xafbc7a37
```
And this says, that it has hex code for 7z, which mean, that it is not supported.

I use this (from example):
```
fs.createReadStream('./packedFolder.7z')
  .pipe(unzipper.Extract({ path: './' }));
```

**Comment by ZJONSSON** [comment]
Thank you for the suggestion.  As I understand it, the 7z spec differs substantially from zip (see [here](http://www.romvault.com/Understanding7z.pdf)) and would probably be better implemented as a separate repo.   However, please feel free to reopen and submit a PR if you think there is a straightforward way to implement in `unzipper`
