### ISSUE TITLE
if zip file that size under 1kb the close event will emit after full extract when use Extract function

### ISSUE THREAD

**Issue by wwl88436384** [ZJONSSON/node-unzipper#56]
hello:
    I found a issue that if zip file that size under 1kb the close event will emit after full extract when use Extract function.for example:
    fs.createReadStream(packagePath).pipe(unzip.Extract({path: extractPath}).on('close', () => {}))
   
   the resolve method of mine is that append a 1kb file in zip when zip a file,so when extract the zip file will correct.for example:
   const fillBuffer = Buffer.alloc(1024);
   archive.append(fillBuffer, {name: '_ignore'})  
please quickly resolve this issue,thank you!

**Comment by ZJONSSON** [comment]
This should be fixed in version 0.9.1 (see [here](https://github.com/ZJONSSON/node-unzipper/pull/68)).   Can you please verify and reopen this issue if that is not the case?
