### ISSUE TITLE
finish/close event emitted after error event and then crashes

### ISSUE THREAD

**Issue by rhodgkins** [ZJONSSON/node-unzipper#57]
Both the `finish` and `close` events get emitted after the `error` event (as `FILE_ENDED`) with the [following ZIP file](https://github.com/ZJONSSON/node-unzipper/files/1852570/bad.zip). Then once this has happened a `TypeError` is thrown from: https://github.com/ZJONSSON/node-unzipper/blob/a0efc1682ce23261f87d1a9c1c47e55b2140fd5d/lib/PullStream.js#L59

I'm not sure whether or not `finish` (or `close`) should be emitted if an error occurs - to my mind they shouldn't, but I can't work out why this ZIP is causing the crash.

~I've managed to stop the crash (but not the multiple events) by checking `__ended` before calling the write's `cb()` - have no idea if this is the correct fix:
https://github.com/bookcreator/node-unzipper/blob/bad-zip/lib/PullStream.js#L59~
The above "fix" actually breaks normal ZIP files.

Reproduction code with code from master branch:

```js
const fs = require('fs')
const unzipper = require('unzipper')

fs.createReadStream('./bad.zip')
    .pipe(unzipper.Extract({ path: './bad' })
    .on('error', err => console.error('error', err))
    .on('finish', () => console.log('finish'))
    .on('close', () => console.log('close')))
```

Output:

```
error FILE_ENDED
close
finish
_stream_writable.js:464
  cb();
  ^

TypeError: cb is not a function
    at afterWrite (_stream_writable.js:464:3)
    at onwrite (_stream_writable.js:455:7)
    at ./node-unzipper/lib/PullStream.js:59:60
    at afterWrite (_stream_writable.js:464:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rhodgkins** [comment]
After looking into it again, there's a more reliable fix here:

https://github.com/bookcreator/node-unzipper/commit/c512d343efeb60e5b4e20f70ef01a2871322a1de

This removes the write callback to prevent it from being called again.

**Comment by ZJONSSON** [comment]
Thanks @rhodgkins, can you recreate this in a test (that fails before and succeeds after)?
PR would be much appreciated - if not I can pull this in directly

**Comment by rhodgkins** [comment]
No problem @ZJONSSON (only issue would be with a failing test case - the ZIP attached to this issue is over 2MB).

I'm not sure if this fixes the issue though? The `finish`/`close` events are still being emitted after the `error` event - like I said above, this seems wrong? Maybe its OK for the `close` event to be emitted but not so sure about `finish`!

**Comment by ZJONSSON** [comment]
@rhodgkins https://github.com/ZJONSSON/node-unzipper/pull/71 Added an `extract` method to `Open` which successfully extracts your file
Also ensure that `finish` is not emitted upon `error`.
Can you take a look?

**Comment by rhodgkins** [comment]
@ZJONSSON sorry for taking so long to get back to you. Yeh this looks all good from my side 👍

**Comment by ZJONSSON** [comment]
Awesome thanks @rhodgkins I'll look at this later today - in the meantime if you have a fix please post

**Comment by ZJONSSON** [comment]
Latest version is: + unzipper@0.9.9
I am able to successfully extract [NotLongerWorking.zip](https://github.com/ZJONSSON/node-unzipper/files/2309488/NoLongerWorking.zip) Can you please verify and let me know? If this issue persist please reopen the ticket
