### ISSUE TITLE
How to stub unzipper?

### ISSUE THREAD

**Issue by VictorCazanave** [ZJONSSON/node-unzipper#58]
Hello,

I use unzipper in a node.js module and everything works well:
```javascript
...
readableStream.pipe(unzipper.Parse())
    .on('entry', (entry) => {
        // Filter and write files like in the doc
        ...
    })
    .on('finish', () => {
        callback();
    });
...
```

Now I would like to unit test my module with Mocha/Sinon/Chai and avoid to really call unzipper using a [stub](http://sinonjs.org/releases/v4.5.0/stubs/) (or something else).
I tried many things but I can't figure out how to handle events (`entry` and `finish`), so the callback() is never called and the test returns a timeout error.

Does anyone have an example of unit test with a "fake" unzipper?

PS: I know it's not really an issue, so if you think it's not relevant, fell free to close it.

**Comment by camlegleiter** [comment]
Seems like that's a bit of a hassle. Would it be easier to pull out each of your event handlers and test them more individually? Testing code like that feels like its closer to an "integration" test since you're verifying different units of work will work together, which would make more sense to actually use `unzipper` as part of the test.

**Comment by VictorCazanave** [comment]
I'm not an expert in testing, so I may have mixed unit and integration tests.
My event handlers are private methods and I didn't plan to test it (I know there is a debate about it).
Actually, the only thing I would like to test is the callback (with or without error):
```javascript
if(isValid) {
    readableStream.pipe(unzipper.Parse())
        .on('entry', (entry) => {
            // Filter and write files like in the doc
            ...
        })
        .on('finish', () => {
            callback();
        });
} else {
    callback(new Error());
}
```
If you think it may be hard to stub `unzipper`, I'll try to use it with a simple .zip file for my tests.

**Comment by VictorCazanave** [comment]
Oops! My bad... Actually my first idea works well but I called the event emit at the wrong place 🤦‍♂️ 
Here is my solution:
```javascript
describe('...', () => {
   let readableStream = null;
   let Parse = null;

   beforeEach(() => {
      readableStream = new stream.Readable({ read: () => null });
      Parse = sinon.stub(unzipper, 'Parse');
      Parse.returns(readableStream);
   });
   
   afterEach(() => {
      Parse.restore();
   });

   it('...', done => {
      myFunctionToTest(..., err => {
         expect(err).to.be.undefined;
         done();
      });
      readableStream.emit('finish');
   });
});
```
Sorry and thanks for you help @camlegleiter
