### ISSUE TITLE
Stop emitting strings in 'error' events

### ISSUE THREAD

**Issue by blake-regalia** [ZJONSSON/node-unzipper#60]
For example, https://github.com/ZJONSSON/node-unzipper/blob/master/lib/PullStream.js#L66

Please conform to the expected 'error' event interface and only emit instances of `Error`, rather than strings. This is as easy as changing this to `new Error('FILE_ENDED')`.

**Comment by ZJONSSON** [comment]
That makes sense, do you have a PR?
