### ISSUE TITLE
Decrypt password protected files

### ISSUE THREAD

**Issue by ZJONSSON** [ZJONSSON/node-unzipper#7]
Spec (section 6.1)
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

See `zipfile` in python for a working implementation

Header check:
https://github.com/jimkang/annoy-node 

ZipDecrypter
https://github.com/python/cpython/blob/master/Lib/zipfile.py#L509-L567

**Comment by stefanKuijers** [comment]
Did you happen to book any progress on this? Curious to hear how far you got. Thanks in advance!

**Comment by ZJONSSON** [comment]
Thanks @stefanKuijers - I think I have figured out a way to do this natively.   Published under `unzipper@0.8.2`.  Currently the decryption methods are only available in `unzipper.Open.file` and `unzipper.Open.url` - and you will have to supply the password to either `file.stream(pwd)` or `file.buffer(pwd)` functions that are available on each file-entry.   Let me know if there are any issues.

**Comment by stefanKuijers** [comment]
@ZJONSSON I've just tried it and it looks like it's working. Thank you for the great work. I'll be using it to build an important feature and am looking forward to using this plugin for it.

**Comment by ZJONSSON** [comment]
Awesome, thanks for the feedback!

**Comment by stefanKuijers** [comment]
I did notice that in case I fill out no password or a wrong password the error event is not triggered. Give me a sec and I will post some example code

**Comment by stefanKuijers** [comment]
## Problem
Unzipping files from a zip with password *does not work*. Files are unzipped but the stream is empty when using a password.

## Code
```
const args = {
    lib: {
        path: './lib',
        file: 'zippedUp.zip'
    },
    id: '12344',
    pass: 'hackMePlease',
    callback: (path) => {
         console.log('unzipped and all. File:', path);
    }
};
unzipper.Open.file(`${args.lib.path}${args.lib.file}`)
		.then((d) => {
			return new Promise((resolve,reject) => {
				const file = d.files.find(item => item.path.match(args.id));
				const tmpFilePath = path.resolve(`${libDir}/${file.path}`);
				
				console.log('file found', file.path, 'write as', tmpFilePath);
				console.log('unzipping', `${args.lib.path}${args.lib.file}`, 'with', args.pass);
				file.stream(args.pass)
					.pipe(fs.createWriteStream(tmpFilePath))
					.on('finish',() => { resolve(tmpFilePath); })
					.on('error',reject)
				;
			});
		})
		.then((tmpFilePath) => {
			console.log('file written', tmpFilePath);
			args.callback(tmpFilePath);
		})
		.catch((e) => {
			console.log('error during opening the file', e);
		});
```

## Input
I created 3 zip files. and execute exactly the *same code (see above)*. 
1. no password
2. password (AES-256)
3. password (ZipCrypto)

## Results
1. The file gets extracted well and is playable (mp4)
2. Password not excepted -> BAD_PASSWORD -> creates an empty file (0 bytes)
3. Password excepted -> creates an empty file

## Conclusion
Password unzipping could work with ZipCrypto but somehow the content of the file gets lost. The pipe is empty. ```file.stream(args.pass).pipe()```

**Comment by stefanKuijers** [comment]
@ZJONSSON Any chance of looking into this soon?

**Comment by ZJONSSON** [comment]
Hey @stefanKuijers  - there are multiple specs for encryption.  I have tackled the basic encryption (see tests)  but some more work would need to be done to address the other cryptos.   I'll keep this on my list - feel free to experiment and do PR if you figure it out?

**Comment by stefanKuijers** [comment]
Thank you for the invitation to cooperate. I would be interested to do but have limited knowledge in node and no time in the coming months. For this reason I chose uncompressed encryption using cryptoJS. 

If I understand it right you assume the code is working with some kind of encryption. Which one?

**Comment by ZJONSSON** [comment]
It's the  `6.1 Traditional PKWARE Decryption` - for more details look at 6.1 in [the spec](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT).  This seems to be the same decryption supported by python [ziplib](https://github.com/python/cpython/blob/master/Lib/zipfile.py#L509-L567)

The encrypted file used in [test](https://github.com/ZJONSSON/node-unzipper/blob/master/test/openFileEncrypted.js) can be found [here](https://github.com/ZJONSSON/node-unzipper/tree/master/testData/compressed-encrypted)

**Comment by stefanKuijers** [comment]
I'm trying to find some kind of desktop app that can create a zip with that encryption. Do you have any suggestions?

**Comment by stefanKuijers** [comment]
I downloaded a trial of PKZIP and chose the traditional password encryption. I use the same code which I posted above but its not working. ```pipe.on('finish', fn)``` and  ```pipe.on('error', fn)``` never get called. The JS process seems to freeze. (takes 25% from my cpu).

**Comment by Bakuenjin** [comment]
So, I was able to extract a password protected zip archive with this tool.
It was **VERY** tricky (mainly because I haven't digged into JS that much yet) and it has some restrictions (the reason I am posting this).
```javascript
unzipper.Open.file(dl.getSavePath()).then((d) => {
    return new Promise((resolve, reject) => {
      for(i = 0; i < d.files.length; i++)
      {
        const file = d.files[i];
        const tmpFilePath = path + "/" + file.path;
        d.files[i].stream(pw)
          .pipe(fs.createWriteStream(tmpFilePath))
          .on('finish', () => resolve(tmpFilePath))
          .on('error', reject);
      }
      
    })
  }).then((path) => {
    console.log('file(s) written to ' + path);
  }).catch((e) => {
    console.log('error while processing archive', e);
  });
```
So this the code that works, but **only** with ZipCrypto encrypted archives and has problems handling subfolders (which means, all files need to be in the "root folder" of that zip archive).

Some clarification for other readers about my code:
`dl.getSavePath()` is the path to the zip archive (path/to/archive.zip) including the file itself in that path.
`path` is the path to the folder, where the zip archive is saved and will be extracted to.
`pw` is obviously the password for decrypting the zip file.

Now the question is:
Is my problem with subfolders easily solveable on my side or is this problem caused by the unzipper?
Is there any possible workaround?

**Comment by ZJONSSON** [comment]
Thank you this is very helpful @Bakuenjin.    We only support basic encryption by the original spec, but I see no reason why subdirectories should not work.  Can you create and upload a file with subdirectories that should work, but doesn't?

**Comment by Bakuenjin** [comment]
Any update on this @ZJONSSON ?
Your node-unzipper is really powerful and useful but I really need to get this working with subdirectories.

**Comment by ZJONSSON** [comment]
Hey sorry for the delay @Bakuenjin I will have some time over the weekend to look at this

**Comment by onsightit** [comment]
> Any update on this @ZJONSSON ?
> Your node-unzipper is really powerful and useful but I really need to get this working with subdirectories.

Zips containing sub-directories of files are not traversed.  unzipper.Parse() just returns a list of the sub-dirs.  I cannot find a way to process the files in the sub-dirs. :(  Maybe a recursive option is needed?

Steve

**Comment by Bakuenjin** [comment]
@onsightit 
As posted above, I found a way to handle subdirs using `unzipper.Open.file()`.
This function returns a Promise with a CentralDirectory object, which has a `files` array containing everything inside your zip archive, even subdirectories and files inside there.

From here you just have to iterate through the array and react accordingly (either create a directory at the directory you are extracting your archive in to, or stream the file by piping a writeStream into it)

Here an example code:

```JavaScript
const unzipper = require('unzipper');
const fs = require('fs');

function unzipArchive(zipPath, extractPath, password) {
    // Opening zip archive, gives us access to its root directory in the .then()-callback
    unzipper.Open.file(zipPath).then((centralDirectory) => {
        return new Promise((resolve, reject) => {
            // Iterate through every file inside there (this includes directories and files in subdirectories)
            for (let i = 0; i < centralDirectory.files.length.length; i++) {
                const file = centralDirectory.files.length[i];
                filepath = path.join(extractPath, file.path);
                // Now this is a very 'quick n dirty' way of checking if it is a subdirectory, but so far it hasn't failed me ;)
                if(file.path.endsWith("/")) {
                    fs.mkdirSync(filepath);
                }
                else {
                    // This can get problematic when your archive contains alot of files, since the file.stream() works async and you have a limit of open writers.
                    // If you fall into that category, my first thought would be using tail-recursion and start the next write in the .on('finished', ...)
                    file.stream(password).pipe(fs.createWriteStream(filepath))
                        .on('finished', resolve)
                        .on('error', reject);
                }
            }
        });
    });
}
```

**Comment by ZJONSSON** [comment]
Thanks @Bakuenjin.   Please reopen @onsightit if you still have problems.

**Comment by SafalTammewar** [comment]
@ZJONSSON i am facing the issue with password protected file inside zip file when i open that file using winrar it open with empty password but when i am trying using unzipper.open.file() it says missing password
