### ISSUE TITLE
Unable to get Promises to work

### ISSUE THREAD

**Issue by DazWilkin** [ZJONSSON/node-unzipper#72]
I assume the typo here is that the `on` events bind to the `pipe` output *not* the `Parse()` output?
```javascript
fs.createReadStream('path/to/archive.zip')
  .pipe(unzipper.Parse()
  .on('entry', entry => entry.autodrain())
  .promise()
  .then( () => console.log('done'), e => console.log('error',e));
```
i.e.
```javascript
fs.createReadStream('path/to/archive.zip')
  .pipe(unzipper.Parse())
  .on('entry', entry => entry.autodrain())
  .promise()
  .then( () => console.log('done'), e => console.log('error',e));
```

I assume also that I need not include a Promise library to use promises? I'm not a Node.JS developer and am struggling to get the following to work, the promise's then|end aren't called:

```javascript
  object.createReadStream()
    .pipe(unzipper.Parse())
    .on("entry", (entry) => {
      var filePath = entry.path;
      var type = entry.type;
      var size = entry.size;
      console.log(`Found ${type}: ${filePath}`);
	  entry.autodrain();
    })
    .promise()
    .then(() => {
      console.log("Zip File Processed");
    }, (err) => {
      console.log(`Zip Error: ${err}`);
    });
```
The code appears to work correctly and iterates over the zip file's contents *but* even though it appears to get through all the entries, neither the promise's `then` nor `err` callback is made.

**Comment by DazWilkin** [comment]
Thank you for the prompt response @ZJONSSON.

It appears this is exactly my problem... 

The library I'm using is not triggering `end`, `error` or `finish` events even though the file is definitively created. Will pursue with those folks, thank you!

**Comment by ZJONSSON** [comment]
Thanks for letting me know @DazWilkin . The input stream might possibly be missing the last bytes of the file as well, as the `unzipper.Parse()` actually closes when the zip file is complete even though a formal `end` event hasn't been received.

In any case, if you are getting all the zip entries you need through, you could "fake" an `end` in a hacky way,  if the input stream has remained silent for a time that is longer than any latency period in the pipeline.

Something like:

```js
const Stream = require('stream');

class TimeoutStream extends Stream.Transform {
  constructor(timeout) {
    super();
    this.timeout = timeout;
  }

  _transform(d, e, cb) {
    clearTimeout(this._timeout);
    this._timeout = setTimeout( () => this.end(), this.timeout);
    cb(null, d);
  }
}

object.createReadStream()
    .pipe(new TimeoutStream(1000))   // automatically end after 1 sec inactivity
    .pipe(unzipper.Parse())
     ......
```

Closing this - please post any new findings or reopen if you find any related `unzipper` issues.
