### ISSUE TITLE
Streams stopped

### ISSUE THREAD

**Issue by djmurf** [ZJONSSON/node-unzipper#77]
We have been using your unzipper library for some time now with great results ( Thanks! )

We did run into an issue with a zip file that had a single corrupt file, it appears that it was missing the EOF, really hard to tell.

Where I was able to trace it to was Pullstream.js in the stream(eof, includeEof) function. 
We are somehow hitting the else in this block of code: 

        if (match !== -1) {
          if (includeEof) match = match + eof.length;
          packet = self.buffer.slice(0,match);
          self.buffer = self.buffer.slice(match);
          done = true;
        } else {
          var len = self.buffer.length - eof.length;
          packet = self.buffer.slice(0,len);
          self.buffer = self.buffer.slice(len);
        }

and len is resulting in a negative value and the streams stop. 

As a workaround, we have patched the function to emit an error when this condition occurs: 
    var len = self.buffer.length - eof.length;

          if ( len < 0 ) { 
            self.removeListener('chunk', pull);
            console.log("*********************************************************")
            console.log("UNZIP::PULLSTREAM ERROR!!!! Buffer less than 0!!!!");
            console.log("*********************************************************")
            self.emit('error', new Error('BUFFER_LESS_THAN_0'));
            this.__ended = true;
            return;
          }

I would be curious if you have a better idea of what might be happening here, and maybe how to better handle it. The error being emitted will abort the entire unzip, when it is really just a single file in the archive that appears to be corrupt. 

I can provide the zip archive that caused this issues if that helps. 

Thanks for the great library & any assistance. 

Dean

**Comment by ZJONSSON** [comment]
Hey Dean, sorry I missed this when you posted it.  I'm not sure what is going on here, can you please send over a zip archive that causes this issue and then I can try to debug?

**Comment by ZJONSSON** [comment]
Hey @djmurf does your offer to share the zip file stand?  If so can you please put here or email me the file.

**Comment by djmurf** [comment]
Ziggy -- Sorry for missing your first response. I had to switch to an alternate zip library after I had opened this. I'll spend some time tomorrow seeing if I can locate the zip file that was causing this. I'll post here either way. Thanks & sorry for the delay.

**Comment by ZJONSSON** [comment]
Awesome, thanks!!
