### ISSUE TITLE
[QUESTION] Last modified date parsing

### ISSUE THREAD

**Issue by dios-david** [ZJONSSON/node-unzipper#80]
Hi everyone,

When I check the `vars` property of an `entry` during unzipping, I get this:

```
{
  versionsNeededToExtract: 20,
  flags: 2048,
  compressionMethod: 8,
  lastModifiedTime: 19920,
  lastModifiedDate: 19764,
  crc32: 3025953602,
  compressedSize: 461,
  uncompressedSize: 947,
  fileNameLength: 100,
  extraFieldLength: 0
}
```

Do you know what is this `lastModifiedTime` + `lastModifiedDate` format and how can I parse it with JavaScript?

Thanks in advance!

**Comment by ZJONSSON** [comment]
The date/time are encoded in MS-DOS format.  Some information can be found here:  https://groups.google.com/forum/#!topic/comp.os.msdos.programmer/ffAVUFN2NbA

If I take the lastModifiedDate in your snippet above and run it through the converter I get a Date back:

```js
function dosDateTimeToJS(date, time) {
  const day = date & 0x1F;
  const month = date >> 5 & 0x0F;
  const year = (date >> 9 & 0x7F) + 1980;
  const seconds = time ? (time & 0x1F) * 2 : 0;
  const minutes = time ? (time >> 5) & 0x3F : 0;
  const hours = time ? (time >> 11): 0;

  return new Date(year, month-1, day, hours, minutes, seconds);
}

dosDateTimeToJS(19764, 19920);
```

We should probably add the parsed date as a variable to the entry

**Comment by dios-david** [comment]
Thanks ZJONSSON, it works!
Yes, probably it would worth to add this as `entry.getLastModifiedDateTime()` or something similar.

**Comment by Dubz** [comment]
I second the motion for adding a JS version to this. I couldn't figure it out either until someone else pointed this issue out to me.

Thanks @ZJONSSON for the simple function to flip this back to JS's date object!
