### ISSUE TITLE
Is there a lib that will zip to S3 as a stream? 

### ISSUE THREAD

**Issue by ianbale** [ZJONSSON/node-unzipper#85]
The ideal feature of this library for my use case it that I can unzip a file in S3 a a stream to process locally in chunks. Essential for some of the large files I am dealing with.  In that respect this lib is perfect for me. So many, many thanks for making it available. Much appreciated.

However I have a reverse use case where I need to  create a zip file on S3 and upload data to it as a stream. I cannot find any libraries that do this. I was wondering if anyone knows of one and can point me in the right direction. For the sake of clarity, I am generating data and need to write that into a zip file on the fly. I do not want to upload local files as a stream.

Failing that, when I have chance I might take a look under the hood of this library in the hope of working out how to do it...

**Comment by claustres** [comment]
https://kalisio.github.io/krawler/ relies on https://github.com/maxogden/abstract-blob-store to perform streaming from/to stores.

**Comment by ZJONSSON** [comment]
This library focuses on the unzipping.  I have used [archiver](https://www.npmjs.com/package/archiver) successfully to stream generated zip files to any output (including s3)

**Comment by ianbale** [comment]
Thanks. In the end I found a library called compressing which did what I needed too.
