### ISSUE TITLE
Extract does exactly nothing

### ISSUE THREAD

**Issue by gooor** [ZJONSSON/node-unzipper#97]
```javascript
  const zipper = fs.createReadStream(filePath).pipe(unzipper.Extract({ path: './' }));
```

Does nothing - no error, no files extracted

```
zipper.on('entry', function(entry) { console.log(entry.path);}
```
Returns correct zip contents.

Using wrong `filePath` throws proper error

Any idea how to run this thing???

**Comment by gooor** [comment]
Seems path cannot be relative - if I pass absolute path then it extracts -> question is where did it extracted this zip when passing relative. Please update README

**Comment by ZJONSSON** [comment]
The extraction is handled by [fstream](https://www.npmjs.com/package/fstream) .writer.  If you need to supply absolute paths you can also define the path with:  `path.resolve(__dirname,'subdirname')`
